### PR TITLE
refactor: sort columns alphabetically in the remove dialog

### PR DESCRIPTION
**Pull request by vince1995**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Approach

The columns in the "remove column" dialog are now sorted alphabetically.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Thanks for this PR! Definitely makes it easier to find a column.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.12](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
