### PR TITLE
feat: allow GraphIQL headers

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

New GraphIQL viewer doesn't allow header configuration

Related issue: #1834

### Approach

Adds header editor to GraphIQL

Screen Shot 2021-10-07 at 12 26 56 am

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
This is not yet ready for review, right?

**Comment by dblythy** [comment]
@mtrezza it is ready for review, are you expecting something else? GraphIQL already supports headers so it's pretty simple to enable them.

**Comment by mtrezza** [comment]
Great, will take a look! I was just asking because no review was requested but it seemed already finished.

**Comment by dblythy** [comment]
No worries, I understand you take on a lot across the repos so I’m always conscious not to be demanding and “request” you review my PRs. I appreciate you have a lot of commitments and will get to things when you can. If something isn’t ready, I’ll mark it as draft 😊

**Comment by mtrezza** [comment]
I am actually specifically looking for PRs to merge here to test and refine release automation. So whenever there is a PR ready for review, just feel free to request in any repo.

You are making a good point regarding how we can use the draft state of PRs. Let me open an [issue](https://github.com/parse-community/parse-dashboard/issues/1848) for discussion.

**Comment by mtrezza** [comment]
@axelhildingson could you test this feature and see if it works as you suggested in #1834?

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
