### PR TITLE
feat: add option to auto-sort columns alphabetically

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #1890

### Approach

Add an autosort button to the manage columns dropdown:

Screen Shot 2022-09-06 at 12 54 35

This will sort columns by: `'objectId', 'email', 'username', 'password', 'createdAt', 'updatedAt','ACL', 'authData'`, and then alphabetically thereafter.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
> This will sort columns by: 'objectId', 'email', 'username', 'password', 'createdAt', 'updatedAt','ACL', 'authData', and then alphabetically thereafter.

Seems to be rather arbitrary order and selection. Any specific reason?

So we get some consistency across classes, I would only sort the common fields to the top which occur in all classes:
- objectId
- createdAt
- updatedAt
- ACL

That order is somewhat hierarchical and temporal. All other fields I would sort alphabetically thereafter.

**Comment by dblythy** [comment]
Well the fields I added are the default fields for the user class, which I think should be at the front too

**Comment by dblythy** [comment]
Changed the default order to `['objectId', 'createdAt', 'updatedAt', 'ACL']`

**Comment by mtrezza** [comment]
> Well the fields I added are the default fields for the user class, which I think should be at the front too

Got it. I'd keep the PR as is. The importance of any field depends on the use case, so however it's sorted will only make so many people happy. Prioritizing the common fields `['objectId', 'createdAt', 'updatedAt', 'ACL']` and sorting the rest alphabetically seems the most neutral approach.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
