### PR TITLE
fix: enabling context menu for read-only cells

### PR DESCRIPTION
**Pull request by 404-html**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
In https://github.com/parse-community/parse-dashboard/pull/1688 cell context menu (my baby 😭) was disabled for read-only cells (eg. `createdAt`).

### Approach

As such data can still be used for filtering this fix is about re-enabling context menu for read-only cells but without "Edit row" option. I've also pushed small performance optimization and improvement to showing long values in context menu.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by 404-html** [comment]
Ready to be reviewed ✅

**Comment by mtrezza** [comment]
Great, I see you are still doing some minor corrections, please feel free to request a review in the "Reviewers" section in the top right corner when this is ready.

**Comment by 404-html** [comment]
Thanks @mtrezza. Sorry, but like last time I'm struggling to find this option, that's all I can do:
image

I wonder if this have something to do with my account. Due to my account name I faced some problems in the past (eg. my profile was throwing 404 page).

**Comment by mtrezza** [comment]
The option is [disabled](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) because you need to be a team member to request a review. Sorry, I thought you already were. Do you want to join the team as a [contributor](https://github.com/parse-community/Governance/blob/main/README.md#contributors)?

**Comment by 404-html** [comment]
Sure, happy to join. People appears to be kind in this team 👍
Will do my best to participate.

**Comment by mtrezza** [comment]
Amazing, I have opened a [poll](https://community.parseplatform.org/t/vote-to-add-404-html-as-a-member/2054) to confirm you.

**Review by mtrezza — APPROVED** [review]
Looks good! Thanks for the fix!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1)

**Pull request merged**
