### PR TITLE
fix: Empty table in data browser when navigating back using the "back” button

### LINKED ISSUE #2415: Showing "No data to display" for the _Role section, even though there are Roles present.
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The message "No data to display" is appearing for the Role section, even though there are Roles present. also not showing any rows in the table.

### Steps to reproduce

1. Create couples of Roles in the _Role secion.

2. Click on "View relation" for any columns users or roles.
Screenshot 2023-04-10 at 11 08 15 AM

3. Click on back icons to go to the main table.
Screenshot 2023-04-10 at 11 08 43 AM

4. Showing no rows with message "No data to display".
Screenshot 2023-04-10 at 11 09 07 AM

### Actual Outcome

Showing no rows with message "No data to display".

### Expected Outcome

During the 4th step, it is expected to display all the rows in a manner similar to the image shown in step 2.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64)`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

NA

### PR DESCRIPTION
**Pull request by patelmilanun**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
when u visit inner class from any field of type relation u can get a back button to fall back to parent class but here it was not fetching that data and rather showing the old data.

Closes: #2415 

### Approach
The current check was not checking for the condition for fetching and updating the data for a type of relation. As the parent class is same for old as well as the new screen, when transitioning we are getting same class name and thus not updating. So I added the condition for relation as well.

### TODOs before merging
None

### CODE REVIEW

**Review by AshishBarvaliya — APPROVED** [review]

**Comment by mtrezza** [comment]
Is this ready for review?

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
