### PR TITLE
fix: Incorrect date picker position in data browser filter dialog

### LINKED ISSUE #2424: After applying the filters, the placement of the date picker is changing.
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

After applying the filter, the placement of the date picker is changing.

### Steps to reproduce

CPT2304151835-1432x694

### Actual Outcome

the placement of the picker is wrong.

### Expected Outcome

Screenshot 2023-04-15 at 6 44 55 PM

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

After applying the filters, the placement of the date picker is changing.

Closes: #2424 

### Approach

After resolving the position issue, I proceeded to test the functionality with multiple datepickers. and discover a new overlapping issue.

CPT2304171819-1105x512

Solution - 
It appears that the current implementation of "setFocus"  in [FilterRow Component](https://github.com/parse-community/parse-dashboard/blob/447b04697ac0e00f1244ef9a4fd5fd9c5b375532/src/components/BrowserFilter/FilterRow.react.js#L23) is being used to focus filter fields. But it should not focus the fields when the filters are active as It leads to above issue.  
 
To address this issue, I propose modifying the implementation of "setFocus" to only focus on the field when it is in edit mode. I have added an "editmode" state to determine when the field is in edit mode, and I have also optimized(memonized) the component to prevent unnecessary re-rendering of "setFocus".

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this ready for review?

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
