### PR TITLE
fix: various UI bugs (e.g. filter data browser, switch app, upload file)

### LINKED ISSUE #1991: Applying filters not working
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
When filtering the data URL changes but the browser doesn't refresh. It doesn't matter if filters are applied from filters section or context menu.

broken-filters

### Steps to reproduce
1. Go to data browser;
2. Click on "Filters";
3. Click on "Apply these filters";
----
1. Go to data browser;
2. Right click on a cell with data;
3. Click on a "Set filter...";
4. Pick any option.

### Actual Outcome
URL changes but nothing happens. Filter panel stays open.

### Expected Outcome
Data browser should refresh and show filtered data. I believe in first scenario filters panel should also close.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `any`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

### LINKED ISSUE #1994: Switching apps not working
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

switching-apps-broken

### Steps to reproduce
1. Go to data browser;
2. Switch to different app;

### Actual Outcome
Data browser performs a refresh but it still shows data from original app.

### Expected Outcome
Chosen app should become selected and browser should show data from it.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `4.10.4`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.11`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

### LINKED ISSUE #2006: File upload in dashboard GUI is not working
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

 Hello everyone. Just tried latest dashboard version 3.3.0 and in Dashboard GUI file uploading don't work. Just nothing happens when trying to add or replace file in a `File` field of object.  No errors in dev tools console and no requests in dev tools network tab. I was using ver 2.1.0 before. It works there. tried 3.2.0 and 3.2.1 - everything works well. So I guess this problem started from 3.3.0 and newer.
Searched for the similar issues hoping find solution but didn't find anything. 
Below you can see screenshot examples of 3 different versions - 3.2.1, 3.3.0 and 4.0.0

#### how it works well on version 3.2.1 and older
parse_dash_3_2_1

#### and how it not works
parse_dash_3_3_0
parse_dash_4

### Steps to reproduce
1. Open dashboard
2. Browser tab select some schema with `File` field
3. Double-click on it to open file-upload dialog
4. Enjoy the result

### Actual Outcome
Nothing

### Expected Outcome
Expected to upload files via dashboard GUI

### Environment
Different projects with different parse-server and nodejs versions - all behaves equal
Docker: mongoDB, mongo-express, parse-server, parse-dashboard

Dashboard
- Parse Dashboard version: ^3.3.0 | 4
- Browser (Safari, Chrome, Firefox, Edge, etc.): Firefox | Chrome
- Browser version: FF 96.0 (64-bit) 

Server
- Parse Server version: 4.5.0 | 4.10.4
- Operating system: my: ubuntu 20.4.3 | docker: alpine linux 3.10 | 3.14
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): both local and remote

Database
- System (MongoDB or Postgres): mongoDB
- Database version: 4
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): both local and remote hosts

### Logs
no logs

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR fixes a few issues (#1991, #1994, #2006) caused by some changes from two of my refactors.

Related issue: #1948 

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Thanks for the quick fix!

I can confirm this fixes:
- https://github.com/parse-community/parse-dashboard/issues/1991
- https://github.com/parse-community/parse-dashboard/issues/1994
- https://github.com/parse-community/parse-dashboard/issues/2006

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.11)

**Comment by cbaker6** [comment]
@visualfanatic I appreciate all of your updates, the dashboard is looking nice! Not sure if it’s related to this, but I when _Role is updated I have to refresh the browser to see updated `roles` in 4.0.0.alpha.15. If I click other classes in the dashboard and then back to _Role, the updates wont show until I do a manual refresh. I’ll open a formal issue shortly…

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.3](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.1)

**Pull request merged**
