### PR TITLE
fix: minor UI layout issues

### LINKED ISSUE #2199: Trivial UI layout issues
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
There are many trivial layout issues in the UI.

### Steps to reproduce
Examples:

Incorrect button position:
image
image

Parse Dashboard version and user text block not vertically centered with logo:
image

Incorrect button spacing:
image

"Show all" cut off:
image

"Add column & continue" should be in the middle, "Add column" should be on the very right:
image

There may be a few more, so when fixing these it would be good to browser through the dashboard a bit more.

### Actual Outcome
n/a

### Expected Outcome
n/a

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `Version 15.5 (17613.2.7.1.8)`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

There are some minor UI issues throughout the dashboard.

Related issue: #2199
Closes: #2199

### Approach

Fixes minor UI issues. Removes footer list and replaces with a button.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks much better!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
