### PR TITLE
feat: keep entered filter value when changing filter operator

### LINKED ISSUE #2029: Keep filter text when changing filter condition
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Changing the data browser filter field (e.g. `objectId`), or the filter condition (e.g. `equals`) clears the filter text.

image

### Feature / Enhancement Description
The filter text should should not be cleared, to make it faster to change filter field or condition.

### Example Use Case
- A class may have multiple email field (e.g. `email1`, `email2`), so when searching for an email address only the field needs to be changed, without re-entering the email address.
- A user has entered the filter text and wants to correct the filter condition afterwards (e.g. from `equals` to `startsWith`), so only the condition needs to be changed, without re-entering the filter text.

### Alternatives / Workarounds
Re-enter filter text.

### 3rd Party References
n/a

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Changing the filter field resets the filter

Related issue: #2029
Closes: #2029

### Approach

If possible, use existing filter

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
There is a bug that converts a boolean value to a text:
1. Select a boolean field and set it to `equals: true`
2. Select a string field and select "equals"; it shows `true` as text

**Review by mtrezza — CHANGES_REQUESTED** [review]
There is a bug that converts a boolean value to a text:
1. Select a boolean field and set it to `equals: true`
2. Select a string field and select "equals"; it shows `true` as text

**Comment by dblythy** [comment]
Good pickup!

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
