### PR TITLE
feat(preventSort): allow preventSort from columnPreferences props

### PR DESCRIPTION
**Pull request by Klaitos**
Hello guys,

I've added a simple piece of code to prevent sorting on some columns described in columnPreferences.
For example : 

```json
{
  "apps": [
    {
      "appId": "local_app_id",
      "appName": "Local",
      "appNameForURL": "local",
      "javascriptKey": "local_javascript_key",
      "restKey": "local_rest_api_key",
      "masterKey": "local_master_key",
      "production": false,
      "serverURL": "http://localhost:1337/api",
      "supportedPushLocales": [
        "en",
        "fr"
      ],
      "columnPreference": {
        "WorkerCV": [
          {
            "name": "createdAt",
            "preventSort": true
          },
          {
            "name": "updatedAt",
            "preventSort": false
          },
          {
            "name": "checksum"
          }
        ]
      }
    }
]
}
```

Capture d’écran 2021-05-20 à 18 14 23

It's my first open source PR so please feel free to comment if needed.

### CODE REVIEW

**Review by mike-down — APPROVED** [review]

**Review by davimacedo — COMMENTED** [review]
Thanks for the PR. That makes sense to me. Would you mind to add some note in README explaining how to use this option?

**Comment by dblythy** [comment]
Nice job! Closes #1497

**Comment by Klaitos** [comment]
> Thanks for the PR. That makes sense to me. Would you mind to add some note in README explaining how to use this option?

Done !

**Review by davimacedo — APPROVED** [review]
LGTM!

**Pull request merged**
