### PR TITLE
fix: Filter string is erased when changing filter condition

### LINKED ISSUE #2585: Filter string is erased when changing filter condition
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

When changing the filter condition from one string condition to another string condition, the filter string is erased.

### Steps to reproduce

1. Open class `_User`
2. Set filter `objectId` `equals` `abc`.
3. Change filter condition from `equals` to `starts with`.

### Actual Outcome

Filter string `abc` is erased.

### Expected Outcome

Filter string `abc` should be kept.

### Environment

Dashboard
- Parse Dashboard version: `6.0.0-ALPHA.11`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`

### PR DESCRIPTION
**Pull request by vardhan0604**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
fixes #2585

### CODE REVIEW

**Comment by vardhan0604** [comment]
Hey @mtrezza can you please review it?

**Review by mtrezza — APPROVED** [review]
Tested in preview environment

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.12](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
