### PR TITLE
refactor: upgrade semantic-release dependency

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Upgrading minimum Node.js version now allows us to upgrade `semantic-release` deps to latest version which requires Node 14.

Another bonus, less vulnerabilities:

Before:
```
found 37 vulnerabilities (4 moderate, 23 high, 10 critical)
```

After:
```
found 6 vulnerabilities (2 moderate, 2 high, 2 critical)
```

Related issue: #1902 

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
Did you look at the changelogs before upgrading a dependency by a major version?

For example, I think semantic release requires node >=14 in our CI environment(s).

**Comment by damianstasik** [comment]
Yes, that's my usual flow, and now that we don't support Node < 14 we are clear to upgrade.

**Comment by mtrezza** [comment]
> now that we don't support Node < 14 we are clear to upgrade.

These are 2 different things:
- with which Node version is the product tested
- which node versions do the CI jobs run with

Did you check the CI job node versions? - There may be multiple workflow files affected.

**Comment by damianstasik** [comment]
> These are 2 different things

I understand that, and my confirmation was in regards to both. We don't use Node.js < 14.20 in CI, I checked that before I created the PR.

**Comment by mtrezza** [comment]
Amazing, just wanted to make sure so we don't overlook anything. Thanks for confirming.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
