### PR TITLE
cell select height fix

### PR DESCRIPTION
**Pull request by fn-faisal**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/1753).

### Issue Description
The border around the cell is no longer covering the whole cell when selecting a cell.

### Approach
The height of the row is different from the height of the cell which causes the small border. Increasing the height of cell and fixing the height of row to match the cell fixes the border issue.

Screenshot 2021-08-05 at 7 05 24 PM

### CODE REVIEW

**Comment by mtrezza** [comment]
It seems the issue is actually that the row is too high, because the text is not vertically centered. So the proper solution would be to reduce the row height. Otherwise the rows seem quite large, which would reduce the number of visible rows per screen.

Can you adapt the fix to reduce the row height to the same as the cell height?

**Comment by fn-faisal** [comment]
@mtrezza I have updated the row height from auto to 31px (same as the cell height). The ROW_HEIGHT was set to 31 but it wasn't reflecting the height of the row. In css, it was set to auto.

**Comment by mtrezza** [comment]
It looks better now, but could you take another look, the bottom margin is still 1px (or 2?) to large:

image

**Comment by fn-faisal** [comment]
> It looks better now, but could you take another look, the bottom margin is still 1px to large. In other words, the cell is still too high:
> 
> image

@mtrezza I have updated the PR.

**Comment by mtrezza** [comment]
Thanks, something is still wrong here, it seems that the content is not centered in all cells equally.

If you take a look at the difference between the first column (`objectId`) and the second column (a column with a pointer), the text is not on the same height:

image

**Comment by fn-faisal** [comment]
> Thanks, something is still wrong here, it seems that the content is not centered in all cells equally.
> 
> If you take a look at the difference between the first column (`objectId`) and the second column (a column with a pointer), the text is not on the same height:
> 
> image
> 
> In the first, non-pointer column the text should be 1 px higher, without changing the cell height.

@mtrezza I have looked into this and it seems like there's a line-height for the cells but the pointer's new layout isn't effected by the line height. I can remove the line-height and increase padding in the cells to compensate the line height.

**Comment by fn-faisal** [comment]
After removing the `line-height` this is what the layout looks like now.
Screenshot 2021-08-11 at 6 29 40 PM

**Comment by mtrezza** [comment]
The text on the left is still 1px higher than the text on the right, could you take another look?

**Comment by fn-faisal** [comment]
@mtrezza I have updated the Features list.

**Comment by fn-faisal** [comment]
@mtrezza I have updated the PR. Here's what the cells looks like now.
Screenshot 2021-08-16 at 7 43 24 PM
Screenshot 2021-08-16 at 7 43 34 PM

**Comment by mtrezza** [comment]
Looking at your screenshot, both texts are new 1 px too high and the pointer icon is cropped off. I suggest you revert the last commit and just try to lower the text of in left field, as I described in my previous [comment](https://github.com/parse-community/parse-dashboard/pull/1754#issuecomment-898721920).

**Comment by fn-faisal** [comment]
@mtrezza I've updated the PR. Here's the new snapshots.
Screenshot 2021-08-16 at 9 36 54 PM

**Comment by mtrezza** [comment]
We are almost there, here is a zoomed in screenshot:

image

The text needs to move up 1 px.
The icon on the left needs to move up by a few pixel.

**Comment by fn-faisal** [comment]
@mtrezza I've updated the PR
Screenshot 2021-08-17 at 5 31 41 PM

**Comment by mtrezza** [comment]
I have fixed the height. For future reference, the structure is simple:

row height is 30px
cell has padding 5px
cell height therefore is 20px

And all is centered.

**Pull request merged**
