### PR TITLE
fix: app icons are cropped in the app list for small screen sizes

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR contains a small fix for the icon cropping issue on smaller screen resolutions. Tested in FF, Opera, Chrome, and Safari.

Related issue: #1850

### Approach
Stop flexbox from shrinking children when there is not enough space, another solution would be adding `min-width` and `min-height` to the `.icon` selector.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by damianstasik** [comment]
Ready for review

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
