### PR TITLE
Sidebar collapse

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Continuation of https://github.com/parse-community/parse-dashboard/pull/1269
Closes https://github.com/parse-community/parse-dashboard/issues/1759

### Approach
- Removed ease-in animation from toolbar (top bar), because side bar also does not animate when collapsing

### TODOs before merging

- [x] Add entry to changelog

### CODE REVIEW

**Comment by mtrezza** [comment]
@tehsunnliu Could you please try this feature out and let me know if you find any bugs?

**Comment by tehsunnliu** [comment]
https://user-images.githubusercontent.com/15224865/129963040-a02aa4f0-0d18-452e-904b-c90c3691b94f.mp4

Hi @mtrezza, I tested the sidebar collapse feature and it works perfectly fine on a desktop browser and fixes the issue of tables going behind the sidebar. However, on a mobile device, as you can see on the video I've attached since users have no option of hovering the mouse on top of the sidebar when it is collapsed, the sidebar cannot be expanded till Core/Push icon is pressed. 

Anyways I think it is not of a big concern.

Thank you once again for completing this feature. I really appreciate it.

**Review by grosscorporation — APPROVED** [review]

**Comment by mtrezza** [comment]
You mean even when you tap on the pin icon, the side bar does not expand?

**Comment by mtrezza** [comment]
@tehsunnliu Thanks for your feedback. Can you try again and see whether it works for you?

**Comment by tehsunnliu** [comment]
Yes!!! it is working as expected. Thank you so much!! for completing this. :smile::smile::smile::thumbsup::thumbsup::thumbsup:

**Comment by tehsunnliu** [comment]
Hi again! Is it possible to release this version? I'm getting errors while installing the dependency as "git dependency" on the server.
When I run on the server running Ubuntu 20.04.2 LTS with 1GB Ram and 2GB Swap.

`npm install https://github.com/parse-community/parse-dashboard.git#663aa39c96b35a4f0e8ba6ddbd4304e07ebe9083`

I get the following error

```
npm ERR! prepareGitDep HTTP error 404 Not Found
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Hint: If github.com is not accessible in your location
npm ERR! prepareGitDep       try setting a proxy via HTTP_PROXY, e.g. 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep       export HTTP_PROXY=http://example.com:1234
npm ERR! prepareGitDep 
npm ERR! prepareGitDep or configure npm proxy via
npm ERR! prepareGitDep 
npm ERR! prepareGitDep       npm config set proxy http://example.com:8080
...
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 

```
On searching this error I found that we need to update `node-sass` version. So, I forked and updated the `node-sass` version and then tried again to install my forked version. However, now I get javascript heap out of memory. I'm not sure what the npm install <GIT_DEPENDENCY> does but 3GB of RAM(1GB RAM and 2 GB Swap) is also not enough to build the package.

If we could have a newer version of parse-dashboard available to download it would be great.
Thank you.

**Comment by mtrezza** [comment]
Yes, we are planning on releasing a new version in the coming days.

**Pull request merged**
