### PR TITLE
feat: Add visual configurator for Parse Dashboard settings

### LINKED ISSUE #2405: Allow settings page to build Parse Dashboard configuration
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Certain features, such as the Dashboard option `ColumnPreferences` are directly build in Parse Dashboard, however there is no way to export them.

### Feature / Enhancement Description

Add a dashboard settings page that helps building static Dashboard configuration

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Currently, it's quite difficult to create `ColumnPreferences`

Closes: #2405

### Approach

Adds a dashboard settings page which has ability to export `ColumnPreferences`, and to create new dashboard users.

### CODE REVIEW

**Comment by dblythy** [comment]
https://user-images.githubusercontent.com/4974769/224528610-1b559824-9d2e-46d9-b789-61714fecc323.mov

Not sure where Uffuzzi is, but here's how this feature functions

**Comment by mtrezza** [comment]
This is a related discussion: https://github.com/parse-community/parse-dashboard/issues/1744 which may be closed by this issue.

I think the concept looks good in the screen recording.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
