### PR TITLE
ci: Restyle preview html

### LINKED ISSUE #2374: Add PR deployment preview
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Reviewing a dashboard PR requires more effort than PRs from other repos because 
- Parse Dashboard is a visual product with UI
- We don't have UI testing as part of the CI

The dashboard PR has to be cloned locally in a development environment to see the effect of most PRs.

### Feature / Enhancement Description

Add a preview deployment to easily review and preview PRs online without having to clone the PR locally.

See https://docs.uffizzi.com/references/uffizzi-ci/#2-install-authorize-the-uffizzi-github-app

### Example Use Case

n/a

### Alternatives / Workarounds

Clone locally.

### 3rd Party References
n/a

### Uffizzi Feedback

- There seems to be an URL issue, see https://github.com/parse-community/parse-dashboard/pull/2370#issuecomment-1406928232:
  > https://https://app.uffizzi.com/projects/5259/deployments

- It would be nice to have all files in a `.uffizzi` directory. Currently we have:
  ```sh
  ./docker-compose.uffizzi.yml
  ./nginx-uffizzi/...
  ```

- When Uffizzi adds a comment it should probably delete any existing Uffizzi comments, otherwise the thread gets full of comments, and these comments are quite long. 

- While deploying a new commit, the preview URL shows an nginx error page; it's unclear whether the deployment / PR has an issue; it would be better to show a "deployment is progress" page
image

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

- Preview HTML low-fi style
- Login credentials hard to find

Closes: https://github.com/parse-community/parse-dashboard/issues/2374

### Approach
- Restyling preview HTML
- Add login credentials to HTML

### TODOs before merging
n/a

### CODE REVIEW

**Comment by mtrezza** [comment]
@ShrutiC-git Could you give a hint about this error? 
https://github.com/parse-community/parse-dashboard/pull/2377#issuecomment-1407412678

**Comment by jpthurman** [comment]
Hi @mtrezza, you can't make changes to the compose in a PR.  Uffizzi recognizes the compose that has been "validated and saved" in the test compose step under project settings in our UI.  

If you want to make a change to the compose what I would recommend is using the test compose function in the UI to test new changes to the compose and then commit those to your default branch.

**Comment by mtrezza** [comment]
Got it, thanks, I'll go ahead and merge this.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
