### PR TITLE
fix: preserve column sorting preferences in data browser

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR fixes order of execution inside `prefetchData` which was causing sorting preferences to be ignored on the first load.

Related issue: #1992

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@404-html does this fix the issue you reported?

**Review by 404-html — APPROVED** [review]

**Comment by 404-html** [comment]
Work like a charm, thanks 🙌

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.15](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.3](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.1)

**Pull request merged**
