### PR TITLE
refactor: upgrade React Router to v6

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #1902 

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Damian, would you be available for a chat on Slack?

**Comment by damianstasik** [comment]
@mtrezza yes, sure! You can reach me at `<REMOVED>`

**Comment by mtrezza** [comment]
@visualfanatic What is the state of this PR? Are you actively working on it?

**Comment by damianstasik** [comment]
@mtrezza I checked changes on `alpha` since my last update here and it looks like I don't have to adjust. Now I am going through each file making sure everything works as expected, and then I think it could be ready to be reviewed.

**Comment by mtrezza** [comment]
Amazing, this will be a great merge!

**Comment by damianstasik** [comment]
@mtrezza what should we do about failing CI due to minimum Node version required by React Router 6?

**Comment by damianstasik** [comment]
@mtrezza I saw that there was an issue to remove Node 12 support, so I quickly did that to unblock this PR with updated router:
https://github.com/parse-community/parse-dashboard/pull/2277

**Comment by mtrezza** [comment]
@damianstasik Is his ready for review? If so, please request from dashboard-review team.

**Review by mtrezza — CHANGES_REQUESTED** [review]
Could you resolve the conflict?

**Review by mtrezza — APPROVED** [review]
Looks good, and what an enormous PR! Waiting for CI...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
