### PR TITLE
Arrays of Pointers dont render correctly #275

### PR DESCRIPTION
**Pull request by fn-faisal**
This is a PR in reference to this issue:- [https://github.com/parse-community/parse-dashboard/issues/275](https://github.com/parse-community/parse-dashboard/issues/275)

The implementation for the issue is to check for the array of pointers in the browser cell and if the cell data is an array of pointers and the length is greater than 1, the cell shows a scroll bar and upon scrolling, other pointers can be viewed in the cell. Upon clicking on a pointer, it takes the user to the row of the pointer class that matches the object id in the pointer. Double click inside the cell (but not on the pointer itself) the pointer array can be viewed/updated.

Screenshot 2021-06-14 at 2 56 03 PM
Screenshot 2021-06-14 at 2 46 43 PM

### CODE REVIEW

**Comment by mtrezza** [comment]
Didn't @dblythy submit a PR recently which shows an array of pointers visually in square brackets? That would probably be the same as this PR?

**Comment by dblythy** [comment]
It was #1650. It was a quick mock-up and I don't think it was ready for production I'm not a react developer so it needed some work. 

I'm all in favour of this PR over mine!!

**Comment by mtrezza** [comment]
Thanks for shedding light on that. Since you already put your brains into it, do you have any feedback for this approach? How is it different from your idea / mockup?

**Comment by davimacedo** [comment]
@fn-faisal could you please fix the conflicts for this one as well?

**Comment by fn-faisal** [comment]
@davimacedo I have resolved the merge conflicts

**Review by davimacedo — APPROVED** [review]

**Comment by mtrezza** [comment]
@fn-faisal Please me sure to always exclude your [index.html](https://github.com/fn-faisal/parse-dashboard/blob/df03167980a33f37c38e094e6ee07a36a2d718e7/Parse-Dashboard/public/index.html) from your PRs. I removed it during review from another PR but it has been merged here.

**Comment by dblythy** [comment]
> Thanks for shedding light on that. Since you already put your brains into it, do you have any feedback for this approach? How is it different from your idea / mockup?

My approach was focused on making sure any array would render properly, whether it be pointers, dates, etc. This is a good start though! Nice job @fn-faisal.

**Comment by davimacedo** [comment]
@mtrezza sorry about that. I haven't noticed the index.html. Thanks for amending.

**Comment by mtrezza** [comment]
Sure, for a second I was happy because I thought Parse Dashboard had a new feature 🙂

**Pull request merged**
