### PR TITLE
feat(Database Browser): Change columns order and visibility

### LINKED ISSUE #106: Hide/Unhide Columns in Data Browser
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=2.1.4 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Feature

Would be a neat feature is you can hide certain fields from showing up in the dashboard based on class. Example hide createdAt, updatedAt. I imagine you can click on the field at the top, and a drop down shows you the option to hide that column.

### LINKED ISSUE #138: A pop-up to order columns more efficiently
When classes have too many fields, it becomes really difficult to re-order columns in the current manner (dragging a column horizontally across the page). If a pop-up/modal was shown with just the fields in a vertical, draggable, list - it would be much easier to sort.

Bonus addition would be to export this order as a JSON, and import it to different Parse Apps (useful for development vs. production apps).

### PR DESCRIPTION
**Pull request by douglasmuraoka**
Allows users to configure the visibility and order of columns in an easier way. In the column configuration menu, a click changes the visibility of the column, and reordering can be achieved by dragging and dropping. There is also the "Hide All" and "Show All" buttons, that changes the visibility of all columns at once.

Closes #106
Closes #138

image

### CODE REVIEW

**Comment by mtrezza** [comment]
Wow this is a nice one!

**Comment by dplewis** [comment]
Perhaps you can add a reset button to sort 

objectId, ...abc..., createdAt, updatedAt, ACL

**Comment by douglasmuraoka** [comment]
@dplewis yeah, that would be nice :)
What do you think about having this done in a second moment? I believe we have a usable feature in hands.

**Comment by dplewis** [comment]
I agree, I should have time today to test this.

**Comment by douglasmuraoka** [comment]
@dplewis that's great! Thank you 👍

**Comment by dplewis** [comment]
@douglasmuraoka I've tried it out and it seems working fine. I have just one additional question. Is it possible to dismiss the menu when clicking outside the box? Thanks!

**Comment by douglasmuraoka** [comment]
@dplewis fixed, external click closes the component :)

**Comment by omairvaiyani** [comment]
Couldn't be happier with this - we have 50+ columns on some of our classes!

**Pull request merged**
