### PR TITLE
feat: remove support and documentation links

### LINKED ISSUE #2184: Remove Support Links
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Some links to support are broken, are considered unnecessary and should  be removed
 
### Steps to reproduce
Click on the links, etc

### Actual Outcome
Shows zero questions in server fault

### Expected Outcome
Have none links
### Environment
Any

Dashboard
- Parse Dashboard version: `4.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `all`
- Browser version: `any`

Server
- Parse Server version: `5`
- Operating system: `any`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `any`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: https://github.com/parse-community/parse-dashboard/issues/2184

### Approach

- Remove dev links
- Increase log out button size for touch UI

### TODOs before merging
n/a

### CODE REVIEW

**Review by MrMartinR — APPROVED** [review]
Changes looks good. 🚀

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
