### PR TITLE
fix: notification to upgrade dashboard for latest features not working

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR fixes the issue with `package-json` not fetching all metadata.

Related issue: #1893

### Approach
Added the `fullMetadata` flag that allows fetching the whole `package.json`.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! Congratulations for re-discovering this neat feature!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-alpha.14](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.14)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
