### PR TITLE
feat: Add Node 20 support; remove Node 14, 16 support

### LINKED ISSUE #2533: Add support for node 20
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Node 20 is not tested in the CI. In addition, node versions 14 and 16 are no longer supported by node

### Feature / Enhancement Description

Add support for node 20 and drop support for node 14 and 16

### Example Use Case

Use dashboard on latest node.

### Alternatives / Workarounds

Devs run and test on their own.

### 3rd Party References

https://nodejs.org/en/about/previous-releases

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Node 20  isn't tested in the CI. In addition, node doesn't support versions 14 and 16 anymore, but they are currently supported by parse-dashboard

Closes: #2533 

### Approach

Add support for node 20. Drop support for 14 and 16.

### TODOs before merging

- [x] Update CI to test node 20
- [x] Update Github action versions to latest

### CODE REVIEW

**Comment by cbaker6** [comment]
Commit message:

BREAKING CHANGE: Removes support for Node 14 and 16

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
