### PR TITLE
Add ProtectedFields dialog and enhance Permissions dialogs

### PR DESCRIPTION
**Pull request by BufferUnderflower**
- Adds Protected Fields dialog
image

clp-protected-fields

- Added an Authenticated row - represents `requiresAuthentication` from schema.
- Allowed adding Array field as PP.
- Fixes incorrect behavior when it was possible to add Relation field as PP (not supported server-side).
- Allows to set Pointer Permissions (PP) per-operation in advanced mode. Previously it was only possible to set write/read groups ( `readUserFields` / `writeUserFields` in schema).  Upon saving the field name will go under corresponding `operation` into `pointerFields` array.   If all (read or write) operations  are checked  - saves into corresponding `readUserFields`/`writeUserFields` array instead. 
parse-community/parse-server#6351 parse-community/parse-server#6352 #1391

image

- Now saving CLP from dashboard does not clear the `protectedFields`.

### CODE REVIEW

**Comment by davimacedo** [comment]
Great job and thanks for the PR! It is a huge update for Parse Dashboard.

I've just had a try. The CLP worked perfectly but the Protected Fields didn't work for me. Nothing happens when I click on "All field allowed. Click to protect.".

Can you please take a look?

**Comment by BufferUnderflower** [comment]
> Great job and thanks for the PR! It is a huge update for Parse Dashboard.
> 
> I've just had a try. The CLP worked perfectly but the Protected Fields didn't work for me. Nothing happens when I click on "All field allowed. Click to protect.".
> 
> Can you please take a look?

I can't reproduce it here unfortunately (safari/chrome/firefox) on macos.
Could it be so that you've tried a class without any custom fields and it is just empty? Default fields are not shown.
Meanwhile i'll handle such case and show a message saying there are no fields that can be protected.

**Comment by BufferUnderflower** [comment]
Also added a scroll hint

scroll-hint

**Comment by davimacedo** [comment]
That was the problem. I hadn't created any field. Nice job!

**Pull request merged**
