### PR TITLE
fix: link icon in pointer cell not visible when cell is too narrow

### PR DESCRIPTION
**Pull request by sadakchap**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/1814).

### Issue Description

When a cell contains a long text value, the link icon is not displayed:

image

Related issue: #1814

### Approach

Use `position:absolute; right: 0` to fix icon on Pill & give text 75% width of total width.

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@sadakchap please feel free to request a review whenever this is ready

**Comment by sadakchap** [comment]
Sure @mtrezza , I think it is ready for review :)

**Review by mtrezza — APPROVED** [review]
Looks good! A nice style fix!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
