### PR TITLE
fix: Uncaught error when editing Number field in Edit Row dialog

### LINKED ISSUE #2324: Dashboard crashes when editing row with modal
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Dashboard crashes when entering invalid(mismatch type) value.
https://user-images.githubusercontent.com/44117648/195969907-2357880e-5b56-49e0-b5ec-c6a02ecd52ba.mov

### Steps to reproduce

1. open edit row modal
2. enter text in Number type field
3. move the mouse cursor(pointer) out of textarea/input
4. Dashboard crashes

### Actual Outcome

Dashboard crashes on entering invalid value.

### Expected Outcome

Either let user enter invalid value and show a message or restrict user to enter invalid values.
Like in Number type field, we should proper Number editor instead of string editor to prevent user from entering invalid value for that field.

### Environment

Dashboard
- Parse Dashboard version: [`latest-alpha`](https://github.com/parse-community/parse-dashboard/commit/d04c5c33626f994bade0249f41dc818476c6d8b2)
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `106.0.5249.119 (arm64)`

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

`Uncaught (in promise) Error: Maximum update depth exceeded. ` is called when typing an empty field or non alpha numberic characters.

Closes: https://github.com/parse-community/parse-dashboard/issues/2324

### Approach

* Allow clearing number field (undefined)
* Prevent non numberic characters from being entered

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.12](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
