### PR TITLE
refactor: upgrade webpack deps

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR upgrades webpack along with style loaders. Due to changes in `css-loader` and change of the exported modules from CSS module I had to change some of the imports in the codebase. There is also the need to change the required node version to the one required by both `style-loader` and `css-loader`. Fortunately at the end there is a lot of dependencies less in the `node_modules`.

Related issue: #1902

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! To clarify, this is a breaking change because the node engine is bumped from 12.0.0 to 12.13.0, is that intended and correct?

**Comment by damianstasik** [comment]
Yes, it is correct and intended, it is only for dev-only though, but there is no way to specify the environment unfortunately so all users would be affected.

**Comment by mtrezza** [comment]
I've merged some other PRs and the min Node.js version is now 12.22.0, so this shouldn't be an issue.

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0)

**Pull request merged**
