### PR TITLE
ci: update test dependencies

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR updates Jest and puppeteer to latest versions. It includes fixes to issues caused by breaking changes in Jest.

As a bonus here is audit summary before and after.

Before:
```
found 124 vulnerabilities (10 moderate, 99 high, 15 critical)
```

After:
```
found 37 vulnerabilities (4 moderate, 23 high, 10 critical)
```

Related issue: #1902

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you resolve the lock-file conflict? When this is ready for merge, please request a review

**Review by mtrezza — APPROVED** [review]
Looks good! Waiting for CI to pass...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
