### PR TITLE
refactor: update copy-to-clipboard to latest version

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This is the first PR from a series that will bring the dashboard's dependencies up to date. I tested it in the data browser and everything works fine. I also checked the changelog and the last few versions contain only bug fixes and a new `onCopy` callback.

Related issue: #1679

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Docker CI fails. Can you replicate that locally?

**Comment by damianstasik** [comment]
Seems unrelated, got the same issue here:
https://github.com/parse-community/parse-dashboard/pull/1894

**Review by mtrezza — APPROVED** [review]
Look good! Waiting for CI to pass.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-alpha.14](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.14)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
