### PR TITLE
Support building on Windows

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/parse-dashboard/issues/1097

### CODE REVIEW

**Comment by dplewis** [comment]
@oallouch Can you check if this works for you?

**Comment by oallouch** [comment]
"npm run dashboard" : the server starts, but it doesn't update when I change a file (I tried to modify the sidebar title in SidebarHeader.react.js)
"npm run build" : seems to work, but I don't see my modification
"npm run pig" : localhost:4041 gives my a blank page

**Comment by dplewis** [comment]
`npm run dashboard` should also call --watch. Did you refresh the browser / clear cache?
`npm run pig` I ran into the same issue, it will need investigation.

**Comment by oallouch** [comment]
ok, "npm run build" does indeed work. I just need to clear the cache.
but --watch doesn't

The PIG issue seems to be module related. Maybe there should be "export default" instead of "module.exports = "

**Comment by JeromeDeLeon** [comment]
I'm using windows and I just run `npm install` and `npm run pig` access `localhost:4041` but got invalid response.
image

**Comment by dplewis** [comment]
@JeromeDeLeon Can you open this in a separate issue? It might get lost here.

Also include any error messages you received. Does `npm run dashboard` work for you?

**Pull request merged**
