### PR TITLE
refactor: use buttons instead of deprecated javascript URLs

### LINKED ISSUE #1941: Use buttons instead of `javascript:` links
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
We are now getting warning messages about usage of deprecated `javascript:` URLs:
```
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;".
```

### Steps to reproduce
Navigate between random pages and you will see this warning. The solution is to replace all of those links with proper buttons which would make the codebase one step closer to the modern React version.

### Actual Outcome
Warning

### Expected Outcome
No warning, no `javascript:` links in the code, no anchors in places where buttons should be used.

### Environment
All

Dashboard
- Parse Dashboard version: n/a
- Browser (Safari, Chrome, Firefox, Edge, etc.): n/a
- Browser version: n/a

Server
- Parse Server version: n/a
- Operating system: n/a
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): n/a

Database
- System (MongoDB or Postgres): n/a
- Database version: n/a
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): n/a

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #1941

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0)

**Pull request merged**
