### PR TITLE
docs: add info about --dev parameter

### PR DESCRIPTION
**Pull request by cyb3rko**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Added a brief explanation of what the `--dev` parameter exactly does to be able to better evaluate if you really need it.

Related issue: #1826

### Approach
n/a

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Also see this: https://github.com/parse-community/parse-dashboard/pull/962

**Comment by cyb3rko** [comment]
Fits to what I added I think. It just means that the security bypasses only work if having the same IP as the dashboard.

**Comment by mtrezza** [comment]
Maybe we can restyle this paragraph as a whole, how about this:

---

The `--dev` parameter disables production-ready security features. This parameter is useful when running Parse Dashboard on Docker.  Using this parameter will:
- allow insecure http connections from anywhere, bypassing the option `allowInsecureHTTP`
- allow the Parse Server `masterKey` to be transmitted in cleartext without encryption
- allow dashboard access without user authentication

> ⚠️ Do not use this parameter when deploying Parse Dashboard in a production environment.

---

This is how I read the changes from #962:

https://github.com/parse-community/parse-dashboard/blob/7c56b757dfb6cd1dd48c75968137c16a31a9565e/Parse-Dashboard/app.js#L91-L101

https://github.com/parse-community/parse-dashboard/blob/7c56b757dfb6cd1dd48c75968137c16a31a9565e/Parse-Dashboard/app.js#L141-L146

That means the dev param bypasses `allowInsecureHTTP` and allows insecure http connections from anywhere, regardless whether from localhost or remote address. That seems to be exactly the intended fix for Docker, because in the PR, [they say:](https://github.com/parse-community/parse-dashboard/pull/962#issue-400949125)

> when running with docker, as the local IP address is different from the dashboard, all the security features would light up

**Comment by cyb3rko** [comment]
I see, so insecure http connections and non-auth access is always allowed on localhost and the `--dev` parameter is only for docker deployment. Alright.

Added your paragraph to the README.

**Review by mtrezza — APPROVED** [review]
Looks good! Thanks for making the docs more understandable!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.1)

**Pull request merged**
