### PR TITLE
fix: Text input cursor jumps to first position when writing long text

### LINKED ISSUE #2412: When the input field is converted into a text area, the cursor jumps to the start
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

When the input field is converted into a text area, the cursor jumps to the start. 
error

### Steps to reproduce

Modify any field that contains a string data type.

### Actual Outcome

moving cursor to start

### Expected Outcome

It should not move the cursor.

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `latest`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

NA

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Updated TextInput Component

Closes: #2412

### Approach

set selection range when focusing Textarea.

### CODE REVIEW

**Review by patelmilanun — DISMISSED** [review]

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by mathieulb** [comment]
My team is on multiple browsers/OSes and we have a similar bug with beta2 and alpha27, but instead it jumps to the end of the text. It seems like the bug I see is the fix for issue 2413. What I do :

- Click in the middle of short text
- Type enough text to make Dashboard switch to the layout of long text

What happens :

- Cursor jumps to the end
- Undo history is cleared
- another issue making it worse when can't undo : can't cancel either, as the Escape key does not do anything, there is no Cancel button, and any blur (un-focus) event saves the mistake I made, and even closing the tab saves it. The only way out is to press reload (with or without shift). No way to revert to any previous value.

If undo history can't be carried between two different widgets that you are swapping (INPUT to TEXTAREA and back), then surely the whole concept of swapping widgets is the wrong solution to whatever problem it is trying to solve.

**Comment by mtrezza** [comment]
@mathieulb could you open a new issue and fill out the template.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
