### PR TITLE
fix: Text selection not visible in modal dialog header

### LINKED ISSUE #1831: Make selected text visible on the Edit modal title
Sometimes we need to copy the objectId, now when we click on this row open the edit modal, but when selecting the text on this modal title, blue area, we can't see that the text is selected.

The fix is just to not set, or remove, this CSS:
```
::selection {
    color: white;
    background: #169cee;
}
```
So, will use the browser default style or set a different color for the background in this style.

Current:
Screen Shot 2021-10-05 at 11 48 33

Should be:
Screen Shot 2021-10-05 at 11 48 41

### PR DESCRIPTION
**Pull request by jadsonlourenco**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #1831
Closes https://github.com/parse-community/parse-dashboard/issues/1831

Screen Shot 2022-11-04 at 11 12 38

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
You suggested:

> The fix is just to not set, or remove, this CSS:
> 
> ::selection {
>     color: white;
>     background: #169cee;
> }

Did you try to remove the selection color and let the browser handle this? I would expect a browser to choose a color automatically that makes the selection distinct enough.

**Comment by jadsonlourenco** [comment]
Yes, I think this is the solution to this issue. Works correctly in my tests on Chrome, Safari and Firefox.

So sorry about the multiple commits, I forgot to remove the commented code.

**Comment by mtrezza** [comment]
Perfect, thanks for your PR!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
