### PR TITLE
Fixes missing supportedPushLocales in #811

### PR DESCRIPTION
**Pull request by montymxb**
The newly added `supportedPushLocales` causes the **Push** section of the dashboard to break if it is not present. This adds a one-line check to set an empty array if push locales are not set. This does not remove the option to set a push locale however, it just provides no options as can be seen below.

localize

### CODE REVIEW

**Comment by montymxb** [comment]
@flovilmart you mean [this](https://github.com/parse-community/parse-dashboard#configuring-localized-push-notifications)?

**Comment by flovilmart** [comment]
Yessir!

**Comment by montymxb** [comment]
Cool, we should be good the if there's nothing else that comes to mind?

**Comment by flovilmart** [comment]
I meant as an alert inside the section, explaining how to set it up.

**Comment by montymxb** [comment]
Ohhhh, you mean as an actual log entry if the localizations are found not to be set?

**Comment by montymxb** [comment]
@flovilmart Just bumping here. Added a console warning to indicate in the logs if push localization is missing altogether, along with a link to the relevant section in the docs.

**Pull request merged**
