### PR TITLE
fix: Dashboard scrolls when selecting row in data browser

### LINKED ISSUE #2545: Dashboard scrolls when selecting row in data browser
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Dashboard scrolls when selecting row in data browser. This has only been observed when a filter is set.

Uploading recording.mov…

### Steps to reproduce

1. Open dashboard collection in data browser; collection needs to be large enough so it contains enough rows to scroll multiple pages; e.g. see screen recording which uses 300 rows.
2. Set filter "objectId exists".
3. Select a row without scrolling down.
4. Scroll down at least 2 pages and select a row --> data browser jump-scrolls up.

### Environment

Dashboard
- Parse Dashboard version: `6.0.0-alpha.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `Version 17.4.1 (19618.1.15.11.14)`

### PR DESCRIPTION
**Pull request by devbymak**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/2547).

### Issue Description

Closes: [#2545](https://github.com/parse-community/parse-dashboard/issues/2545)

### Approach

prevent scroll to cell on click row checkbox (check prev props with current to detect)

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you describe in the PR above the bug you found and how you fixed it?

**Comment by devbymak** [comment]
I've updated the description of the approach; the other points have been discussed in the issue.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
