### PR TITLE
Exclude hidden fields 

### PR DESCRIPTION
**Pull request by sadakchap**
Get column preference key correctly from local storage to exclude hidden fields values

### CODE REVIEW

**Comment by mtrezza** [comment]
Is this ready for review?

**Comment by sadakchap** [comment]
@mtrezza, thanks for waiting. This pr solves issue https://github.com/parse-community/parse-dashboard/issues/1716.

https://user-images.githubusercontent.com/44117648/127798381-01a01b25-4911-4573-91a7-dff3e128f591.mp4

**Comment by sadakchap** [comment]
@mtrezza, I believe that this pr this ready for a review.

**Comment by mtrezza** [comment]
Thanks for your patience, yes, I am looking at it right now.

**Comment by mtrezza** [comment]
Great, it fixes the issue. I notice that it also fetched data from server for
a) fields that still contains data: hide a field, then show the same field
b) fields that are always sent from server, e.g. `createdAt`, `updatedAt`, `objectId`, `ACL`
c) password field in user, which is always empty

Can we optimize this, at least (b)?

**Comment by sadakchap** [comment]
> I notice that it also fetches data from server for:
> 
> a) fields that still contains data (hide a field, then show the same field)
> b) fields that are always sent from server, e.g. `createdAt`, `updatedAt`, `objectId`, `ACL`
> c) password field in `_User`, which is not transmitted
> 
> Can we optimize this, at least (b)?

Sure we can, could you please first clarify these points ?

a) do you mean, _when it is making request  everytime we un-hide any field without hitting refresh btn_. If yes then, I did thought of making request only if we can not find that field's value in all of the rows. But, it is also possible that all rows contain `undefined` for that field and we will make another request just to get back `undefined` from server.
b) I thought of using `include` query, but it seems like server always sends back these `createdAt`, `updatedAt`, `objectId` fields. 
c) do you mean, when it makes request for unhiding `password` field ?

**Comment by mtrezza** [comment]
Sure, let me try to clarify...

a) the dashboard should not fetch data from server, if a field is hidden and then un-hidden. When a field is hidden, the data of the field is still cached, unless the user hits the refresh button between hiding and un-hiding.

b) the dashboard should not fetch data from server if any of the createdAt, updatedAt, objectId, ACL fields are un-hidden, because these fields are always cached, because they are always fetched from server and never excluded.

c) the dashboard should not fetch data from server if the password field is un-hidden, because the password field is never sent from server as a security precaution, so there is no point is fetching data.

**Comment by mtrezza** [comment]
@sadakchap Do you want to address these issues in this PR, or should we merge and leave this as potential improvement in the future? The PR is already an improvement as it is.

**Comment by sadakchap** [comment]
Thanks for your patience @mtrezza . I am trying to implement suggested changes. I think it would be good to merge this pr after this changes. :)

**Comment by mtrezza** [comment]
Great! Thanks for looking into this.

**Comment by sadakchap** [comment]
@mtrezz, Thanks for waiting. I think now it is ready for a review.

**Comment by sadakchap** [comment]
@mtrezza , Thanks for waiting. I think now it is ready for a review.

**Comment by mtrezza** [comment]
Looks good, just one minor thing:
1. Hide all columns
2. Click on "refersh"
3. Click on "Manage columns" > "Show all" --> doesn't load the empty columns

Could you fix that? That's about the only bug I found.

**Comment by sadakchap** [comment]
> Could you fix that? That's the only bug I found, then we should be good for merge.

Sure, here it is https://github.com/parse-community/parse-dashboard/pull/1734/commits/95b02e7b8c362edbaec70b90f3d0155e75566656!

**Review by mtrezza — APPROVED** [review]
Works great, thanks for this feature!

**Pull request merged**
