### PR TITLE
refactor: Add lint and prettier

### LINKED ISSUE #2467: Add linting to repository
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The code is not (properly) linted, causing varying code styles.

### Feature / Enhancement Description

Enforce proper lint rules.

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-dashboard/issues/2467

### Approach

- Add husky pre-commit hook for prettier and lint
- Add lint rules
- Minor refactor to fix lint errors

### CODE REVIEW

**Comment by mtrezza** [comment]
This is quite a large change across the whole codebase; added prettier and a few lint rules to get rid of code style inconsistencies and this back-and-forth of custom code style adjustments in PRs. The rules are consistent with the rules for parse-server and parse-js-sdk - more or less that is, because they differ slightly from repo to repo.

@parse-community/dashboard please take a look and let know if there's any style change that would not be appropriate for this code type. For example, this codebase contains HTML tags which other repos don't have and prettier or lint replaces the single quotes with double quotes when used in HTML tags.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.28](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
