### PR TITLE
fix: Dashboard may display blank page when selecting an app after login

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related: https://github.com/parse-community/parse-dashboard/issues/2374

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by dblythy** [comment]
I think this should fix https://github.com/parse-community/parse-dashboard/issues/2374#issuecomment-1407173616

**Comment by dblythy** [comment]
@mtrezza I think this should fix the issue, how do we get the preview to show?

**Comment by dblythy** [comment]
Does the pr preview auto-update when new commits are pushed? I'm not sure it does, as the dashboard has retained login between commits

**Comment by mtrezza** [comment]
Yes it should, but it takes a while.

**Comment by dblythy** [comment]
Do you have any tips for debugging? Seems to work fine locally but getting this error on the preview

Screen Shot 2023-01-28 at 11 50 15 am

**Comment by mtrezza** [comment]
I think it has something to do with the URL in the browser that is parsed there? What you could do it output the value to the browser JS console that should be split so you see what value is causing this. My shot in the dark here is that it has something to do with the URL `https://pr-2375-deployment-12561-parse-dashboard.app.uffizzi.com/`, but that's just a guess.

**Comment by mtrezza** [comment]
I think you are right, you may have to close and re-open the PR to redeploy the preview, then it takes about 15 mins.

**Comment by mtrezza** [comment]
Here's the issue:

```js
const appId = 'parse';
const path = '/apps/MyParseApp/browser';
const route = path.split(appId)[1].split('/')[1]; // throws because path.split(appId)[1] == undefined
```

Is this a misconfiguration of the dashboard?

Btw I'm not sure the `route` logic works in all cases, for example if `appId` is `apps` like:
`apps/apps/browser/_Installation`

**Comment by ShrutiC-git** [comment]
hey @mtrezza @dblythy ~

The previews should be updated (without having to close and reopen the PR) as you push commits to that open PR. It could be the case that @dblythy you were seeing a cached version of the preview..?

Once commits are pushed to the PR, this triggers build and deploy again — so the preview gets updated, or you'll have a new preview in case the old one was deleted/expired. 

Was the Uffizzi CI console unable to help here? Ideally, as the containers get rebuilt, the Uffizzi CI will indicate that the containers are building and when the preview was last updated. Were you all not seeing that?

**Comment by dblythy** [comment]
I had to close and re-open, I tried clearing cache and reloading and didn't work.

This is ready for review

**Comment by ShrutiC-git** [comment]
thanks for letting me know, @dblythy. 
The desired behavior is the preview gets updated with new commits. It could be a configuration issue. I'll take a look into what's going on.

**Comment by gadkins** [comment]
@dblythy @mtrezza  

Let me clarify Uffizzi behavior:

- You do not need to close and reopen PRs every time you push a new commit
- Uffizzi is receiving webhooks on every commit, so it will rebuild your application each time.
- Each time it rebuilds a new commit, it will preserve the state from the previous build if volumes are mounted in the compose. This tells Uffizzi to preserve this data as long as this PR is open.
- If you close a PR, Uffizzi will destroy the preview and all its state. If you reopen the PR, you will get an fresh environment with empty volumes and a new comment. 
- On new commits, Uffizzi will update the existing comment on the PR. It will not post a new comment. The multiple comments you are seeing are caused by opening and closing the PR several times.
- You can see which commit is deployed in the [Uffizzi Dashboard](https://app.uffizzi.com/sign_in), along with the timestamp:

Screen Shot 2023-01-27 at 11 35 52 PM

**Comment by mtrezza** [comment]
Let's try to keep the discussion about Uffizzi on https://github.com/parse-community/parse-dashboard/issues/2374 otherwise we have bits all over unrelated PRs

**Comment by mtrezza** [comment]
I've opened https://github.com/parse-community/parse-dashboard/issues/2374 to discuss the Uffizzi integration. Let's try to keep the discussion there, to keep this topic consolidated and make it easier for others to follow. I will respond there.

**Review by mtrezza — APPROVED** [review]
Looks good! Thanks for the quick fix.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.7](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
