### PR TITLE
feat: Execute script for selected rows

### LINKED ISSUE #2497: Execute script for selected rows
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

A script can currently only be executed per row, as a separate manual step per row. This requires repeated steps when a script should be executed for multiple rows.

### Feature / Enhancement Description

Allow to execute a script on all selected rows.

### Example Use Case
n/a

### Alternatives / Workarounds
None

### PR DESCRIPTION
**Pull request by patelmilanun**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Currently we can't execute a script for selected rows directly and we have to execute it row by row manually.

Closes: #2497 

### Approach
Added an option in menu with other mass selection action. With this after selection of rows, user can select a script from dialog to execute on those selected rows.

### TODOs before merging
NA

### CODE REVIEW

**Review by mtrezza — CHANGES_REQUESTED** [review]
Nice work!

Just some suggestions:
1. I believe the scripts feature isn't well placed in the "Edit" menu. It also takes too long to find it beneath all these menu items, which slows down the workflow, which is the opposite of what the scripts feature intends to do. Let's dedicate its own new menu  "Script > Run script on selected rows..." between "Security" and "Edit".
2. Use "run" instead of "execute" script in the dialog for easier reading:
   image

3. When clicking on the "Run script" button again while the script is running, the counter displayed in the button increases to more than the selected rows; the button should be disabled while the script is running.
4. The cancel button should be enabled to cancel the script execution, or at least close the dialog. Otherwise, if the server does not respond, the user is stuck in the dashboard until the request times out.

**Comment by patelmilanun** [comment]
I have 2 questions here.

1. Can you provide me icon for toolbar "Script" item.
2. Your 3 & 4 point can't be implemented in current arrangement as the modal does not provide a way to customize behavior of cancel and submit button. Should I add the code to the core modal component?

**Comment by mtrezza** [comment]
> Can you provide me icon for toolbar "Script" item.

I'd use the `gears` icon we already have in sprites.svg: 
image

> Should I add the code to the core modal component?

I believe so, because otherwise a double click executes the script twice on an object which could be considered a bug that the dashboard allows that.

**Comment by mtrezza** [comment]
@patelmilanun Just a friendly ping in case you haven't seen my previous comment; would be great to get this feature merged.

**Comment by patelmilanun** [comment]
Yes, I've seen you message but currently busy in finding a job so once I get some time, I'll again look into it. By the way do you know anyone who can help me in getting a job.

**Comment by mtrezza** [comment]
Sure thing whenever you are ready. If you are experienced with Parse Server you could post your availability in our community forum where we have a jobs section; other than that I could recommend our bounty program (of which this issue is a part of).

**Comment by mtrezza** [comment]
I've made the changes except for 3&4, which we can add later on. I believe releasing the feature as-is provides outweighs the 2 flaws that can be polished out later on.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
