### PR TITLE
fix: manual column preferences are overwritten by `columnPreference` option on page refresh

### LINKED ISSUE #1882: Using `columnPreferences`: Settings via UI are not cached
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

When using the `columnPreferences` setting it causes that settings that are made via `Manage Columns` (or the width of a column) are not ~~cached~~ visible on the next page view. The cache gets overwritten on the next page view [here](https://github.com/parse-community/parse-dashboard/blob/306e7a99dc036c94f11070e57a37f14f4c3a456a/src/lib/ColumnPreferences.js#L78).

### Steps to reproduce

- use  `columnPreferences` setting 
- show or hide a column via `Manage Columns`
- reload page

### Actual Outcome

The columns that are made visible via `Manage Columns` are hidden.

### Expected Outcome

The columns that are made visible via `Manage Columns` should be still visible.

### Environment

Dashboard
- Parse Dashboard version: [latest alpha branch ](https://github.com/parse-community/parse-dashboard/tree/306e7a99dc036c94f11070e57a37f14f4c3a456a)

PR #1881 would fix that.

### PR DESCRIPTION
**Pull request by vince1995**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Approach
It feels like a bug that the `columnPreference` from the settings are not overwritten by the user settings from the UI. This PR solves this.

### TODOs before merging

- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@vince1995 Could you please open an issue with more information to discuss this, and reference it here?

**Comment by vince1995** [comment]
fixes #1882

**Review by mtrezza — APPROVED** [review]
Looks good! Makes sense to overwrite the config with the manually set column prefs.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.12](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
