### PR TITLE
refactor: Upgrade various dependencies

### LINKED ISSUE #1902: Outdated dependencies
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Currently, most of the dependencies from `package.json` are outdated, some of them have a vulnerability reported by `npm audit`. I created this ticket to keep track of the progress, as I think the best way to get everything updated is to update everything one by one which helps with testing and debugging what went wrong.

### Steps to reproduce
Run any command that checks for dependency updates.

### Actual Outcome
- [x] [@babel/runtime](https://github.com/parse-community/parse-dashboard/pull/1938)                            
- [ ] bcryptjs                                  
- [ ] commander                                 
- [ ] [graphiql](https://github.com/parse-community/parse-dashboard/pull/1907)                                  
- [ ] graphql                                    
- [ ] history                                    
- [x] [immutable](https://github.com/parse-community/parse-dashboard/pull/1900)                                  
- [x] [package-json](https://github.com/parse-community/parse-dashboard/pull/1904)                              
- [ ] react                                       
- [ ] react-ace                                 
- [ ] react-dnd                                  
- [ ] react-dnd-html5-backend                    
- [ ] react-dom                                   
- [x] [react-helmet](https://github.com/parse-community/parse-dashboard/pull/1906)                              
- [x] [react-popper-tooltip](https://github.com/parse-community/parse-dashboard/pull/1901)                      
- [ ] react-redux                               
- [ ] [regenerator-runtime](https://github.com/parse-community/parse-dashboard/pull/1945)
- [ ] [semver](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@actions/core](https://github.com/parse-community/parse-dashboard/pull/1947)
- [x] [@babel/core](https://github.com/parse-community/parse-dashboard/pull/1938)                               
- [x] [@babel/plugin-proposal-decorators](https://github.com/parse-community/parse-dashboard/pull/1938)         
- [x] [@babel/plugin-transform-regenerator](https://github.com/parse-community/parse-dashboard/pull/1938)       
- [x] [@babel/plugin-transform-runtime](https://github.com/parse-community/parse-dashboard/pull/1938)           
- [x] [@babel/preset-env](https://github.com/parse-community/parse-dashboard/pull/1938)                         
- [x] [@babel/preset-react](https://github.com/parse-community/parse-dashboard/pull/1938)                       
- [ ] [@semantic-release/changelog](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@semantic-release/commit-analyzer](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@semantic-release/git](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@semantic-release/github](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@semantic-release/npm](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] [@semantic-release/release-notes-generator](https://github.com/parse-community/parse-dashboard/pull/1947)
- [ ] all-node-versions                         
- [x] [babel-loader](https://github.com/parse-community/parse-dashboard/pull/1938)                              
- [ ] [core-js](https://github.com/parse-community/parse-dashboard/pull/1945)
- [ ] cross-env                                 
- [x] [css-loader](https://github.com/parse-community/parse-dashboard/pull/1939)                                
- [ ] [eslint](https://github.com/parse-community/parse-dashboard/pull/1946)
- [ ] [eslint-plugin-jest](https://github.com/parse-community/parse-dashboard/pull/1946)
- [ ] [eslint-plugin-react](https://github.com/parse-community/parse-dashboard/pull/1946)
- [x] [http-server](https://github.com/parse-community/parse-dashboard/pull/1903)                                
- [ ] jest                                       
- [ ] marked                                    
- [x] [node-sass](https://github.com/parse-community/parse-dashboard/pull/1939)                                 
- [ ] path-to-regexp                            
- [ ] puppeteer                                 
- [ ] react-test-renderer                         
- [x] [sass-loader](https://github.com/parse-community/parse-dashboard/pull/1939)                                
- [ ] [semantic-release](https://github.com/parse-community/parse-dashboard/pull/1947)
- [x] [style-loader](https://github.com/parse-community/parse-dashboard/pull/1939)                              
- [x] [webpack](https://github.com/parse-community/parse-dashboard/pull/1939)                                    
- [x] [webpack-cli](https://github.com/parse-community/parse-dashboard/pull/1909)                               
- [ ] [yaml](https://github.com/parse-community/parse-dashboard/pull/1947)

### Expected Outcome
There should not be any outdated dependency, or at least all dependencies included in `npm audit` should be fixed. 

### Environment
Node v14.17.3

Dashboard
- Parse Dashboard version: 3.3.0-alpha.14
- Browser (Safari, Chrome, Firefox, Edge, etc.): n/a
- Browser version: n/a

Server
- Parse Server version: n/a
- Operating system: n/a
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): n/a

Database
- System (MongoDB or Postgres): n/a
- Database version: n/a
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): n/a

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This is a combined PR containing a few build-related dependency upgrades.

Closes: #1902

### Approach
I tested the dashboard after the upgrade and everything works fine.

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
Shouldn't we have dependabot automatically open PRs to keep dependencies up to date

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
