### PR TITLE
fix: preserve previous condition field value on constraint change

### PR DESCRIPTION
**Pull request by sadakchap**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/1918).

### Issue Description

The value field is emptied when switching between filter conditions.

Related issue: [#1918](https://github.com/parse-community/parse-dashboard/issues/1918)

### Approach

When changing condition, if previously condition field value(compareTo) was set, tthen use previously set compareTo value instead of default compareTo value.

### TODOs before merging

- [ ] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@sadakchap kindly request a review when this ready.

**Comment by sadakchap** [comment]
@mtrezza I think this pr is ready for review :)

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.2-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.1.2-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.2-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.1.2-beta.1)

**Pull request merged**
