### PR TITLE
fix: File uploading status not updating in data browser

### LINKED ISSUE #2274: File uploading status not changing after uploading completed
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

https://i.ibb.co/JHcYx8D/Screenshot-at-Sept-18-02-15-34.png

- File uploading status not changing after uploading completed, 

When user updates a file in a field it indefinitely shows "uploading..." status but we can see the uploaded file in s3, it should change to  "completed" or filename after finishing uploading operation

- Change label from "uploading..." to filename or "upload pending" or "upload waiting confirmation" or something more convenient before pressing add button

Currently when users select a file from device it's showing "uploading..." label in the selected view  but actually, files are not getting uploaded at that point, file uploading only starts when the user press add button, this is a confusing implementation users waits for this 'uploading...' label to change to something like 'completed', it's a bad UX 

### Steps to reproduce

- Update a file in dashboard

- Select a file to upload in dashboard

### Actual Outcome

"Uploading..." status inside view keeps displaying even after the upload is completed
Showing "Uploading..." before pressing add button

### Expected Outcome

- "Uploading..." status should change to "complete" or filename when uploading operation finishes

- Show "Uploading..." only after pressing add button, before that provide appropriate label

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `105.0.5195.125 (Official Build) (x86_64)`

Server
- Parse Server version: `5.2.5`
- Operating system: `Ubuntu 22.04.1 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote-AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.12`
- Node version `v18.1.0`
- FileAdapter - s3 (aws)
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs

No logs or error messages on the browser

### PR DESCRIPTION
**Pull request by patelmilanun**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
there was a problem of status change when u do upload a file. The problem was that even after the file is uploaded there is no way the user is getting notified of it as the field will show uploading.. even though the upload is completed.

Closes: #2274 

### Approach
So the issue is that we are saving the row before saving of file gets completed and thus we are not able to identify that the change has occurred. This PR resolve it by resolving the pending file upload promise if its there and than re-render the cell.

### TODOs before merging
None

### CODE REVIEW

**Comment by patelmilanun** [comment]
How one can see the preview build which uses mongodb as the given preview url is using postgreSQL

**Comment by mtrezza** [comment]
What do you mean

**Comment by patelmilanun** [comment]
So if I open the preview link generated with Uffizzi, we are not able to do file upload as it is integrated with mongoDB only I think, and in order to take a look at if my changes fixed the issue or not the preview link should use mongoDB. If u look at the logs for the build you can see we are using PostgreSQL and not the mongoDB. This problem is specific to mongoDB.

So for case like this where we have to only see our changes using mongoDB as our database is it possible?

**Comment by mtrezza** [comment]
Got it, the current set up is limited to what it is. We could look into expanding this, but that's a separate issue we'd need to explore. For now we'd just test this locally and merge if we can verify the issue is fixed.

**Comment by mtrezza** [comment]
Could you test this locally and upload some screenshots, so it's easier to review?

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.7](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
