### PR TITLE
feat: improve distinction between deletion confirmation dialogs

### LINKED ISSUE #2239: Change row batch deletion confirmation entry
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

This is a UX issue. The confirmation dialog to delete selected rows, to delete all rows and to delete the whole class require to enter the class name. All 3 dialogs look similar. The issue is that the dialogs may be mistaken for each other. Also the buttons in the menu to perform these actions are next to each other.

Screen Shot 2022-08-16 at 11 38 04

Screen Shot 2022-08-16 at 11 30 37

Screen Shot 2022-08-16 at 11 24 38

Screen Shot 2022-08-16 at 11 24 28

### Steps to reproduce
1. Delete selected rows 
2. Delete all rows
3. Delete class

### Actual Outcome
Described above

### Expected Outcome

Make the dialogs more distinguishable, for example:

- The dialog to delete N rows should not request to enter the class name but the word "delete selected"
- The dialog to delete all rows should not request to enter the class name but the word "delete all".
- The dialog to delete the whole class should stay as is and request to enter the class name.

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`

### Logs
n/a

### PR DESCRIPTION
**Pull request by sadakchap**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/2239).

### Issue Description

UX issue. The confirmation dialog to delete selected rows, to delete all rows and to delete the whole class require to enter the class name. All 3 dialogs look similar. The issue is that the dialogs may be mistaken for each other. Also the buttons in the menu to perform these actions are next to each other.

Related issue: #2239 

### Approach

Updated RowDeleteDialog component, to show different confirmation text based on row selection(props.selection).

selection length >= 10 --> confirmationText = "delete selected"
selected all                   --> confirmationText = "delete all"

Note: for deleting whole class there is different dialog [component](https://github.com/parse-community/parse-dashboard/blob/alpha/src/dashboard/Data/Browser/DropClassDialog.react.js)(No changes there).

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@sadakchap When this is ready for review, kindly request a review from @parse-community/dashboard-review

**Comment by mtrezza** [comment]
@sadakchap When this is ready for review, kindly request a review from `@parse-community/dashboard-review`

**Comment by sadakchap** [comment]
I think this pr ready for a review. 
@parse-community/dashboard-review Please let me know about your thoughts.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
