### PR TITLE
fix: Dashboard not building for docker platform arm64/v8

### LINKED ISSUE #2501: Published docker image has no matching manifest for linux/arm64/v8
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Starting with release v5.1.0 the published Docker image on Docker Hub no longer has a matching manifest for linux/arm64/v8. When running the Docker image, this message is returned when pulling the image:
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```
With release 5.0.0 there is no problem. Is there a specific reason, why the published image was changed? This prevents us from using the latest version locally (M1 Mac) and in deployments (Linux).

### Steps to reproduce

Pull the image on Linux/Mac M1/ARM.

### Actual Outcome

`no matching manifest for linux/arm64/v8 in the manifest list entries`

### Expected Outcome

Image can be run on linux/arm without issue as before.

### Environment

Starting with v5.1.0 the problem occurs, also with 5.2.0.

Dashboard
- Parse Dashboard version: `> 5.0.0`

Server
- Parse Server version: `not relevant`

Database
- System (MongoDB or Postgres): `not relevant`

### Logs

`no matching manifest for linux/arm64/v8 in the manifest list entries`

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Docker images will not build locally or remotely for `arm64/v8`.

Closes: #2501 

### Approach

Update dev dependency packages preventing image building for `arm64/v8`, specifically `puppeteer` version `18.0.5->22.6.1`.

These changes allow for building locally. There's still an issue for building via the CI, https://github.com/parse-community/parse-dashboard/pull/2534#issuecomment-2043762194

### TODOs before merging

- [x] Ensure CI passes

### CODE REVIEW

**Comment by stephannielsen** [comment]
@cbaker6 is this closing this issue? #2501 

Would be awesome!

**Comment by cbaker6** [comment]
@stephannielsen this branch does address the issues for building for `arm64/v8`. If you build on apple silicon from this branch locally, it should work fine. Unfortunately, the buildx emulation cross build takes way too long which is why it's failing in the CI.

You can either build the respective branch locally or you can use my image (details in the README) https://hub.docker.com/r/netreconlab/parse-hipaa-dashboard

**Comment by mtrezza** [comment]
I have updated the workflow to run for arm64/v8, it should also build the docker image when this PR gets merged. The CI time increases significantly by ~25mins. We may temporarily disable the docker build for arm64/v8 in the ci workflow, assuming that if it builds for amd64, it will also build for arm64/v8 in the release workflow. This is a temp solution until linux arm64 runners become available in GitHub Actions, presumably by EOY 2024.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.16](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.16)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
