### PR TITLE
refactor: remove unnecessary async/await expressions

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
I noticed that the `getPointerDefaultKey` method in `src/lib/ColumnPreferences.js` awaits the value from local storage, but that is unnecessary as the returned value is not a `Promise`. I looked through the code to see if I can find similar cases and I did, and this PR contains a tiny refactor that gets rid of those unnecessary `async`/`await` expressions.

Related issue: #1873

### Approach
Look for all `async` and `await` keywords and determine whether they are required or not.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by damianstasik** [comment]
Ready for review

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.9](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
