### PR TITLE
fix: view relation dialog requires browser refresh when navigating

### LINKED ISSUE #2171: "View Relation" dialog requires browser refresh to work
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

When clicking on the "View Relation" button on relation fields, it leads to a bugged view which basically needs to be manually reloaded / refreshed to work.

### Steps to reproduce

Go to any relation field you have, click on "View Relation".  This will not load until you manually refresh the view.

### Actual Outcome

Half-loaded / bugged view.

### Expected Outcome

There should be no need to manually refresh the view to see the relations.

### Environment

Parse Server 5.2.1
Parse Dashboard 4.1.1
Express 4.18.1

Dashboard
- Parse Dashboard version: `4.1.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari, Chrome`
- Browser version: `Safari 15.5, Chrome 102.0.5005.115`

Server
- Parse Server version: `5.2.1`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Tested on both Local and on Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local and MongoDB Atlas`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Relation requires page reload when navigating backwards and forwards

Related issue: #2171
Closes: #2171

### Approach

Loads pointers on setting relation, and loads data when going back

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@Sarun1001 Could you try out this PR and let us know whether this fixed the issue?

**Review by mtrezza — APPROVED** [review]
Looks good!

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.17](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.17)

**Comment by Sarun1001** [comment]
@mtrezza It's resolved, Now relations load without refreshing

**Comment by Sarun1001** [comment]
@dblythy Thanks again 👍

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
