### PR TITLE
fix: Data browser redirects to wrong class when changing app

### LINKED ISSUE #2519: Browser Dashboard redirect to wrong class when changing App from AppsMenu
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Browser Dashboard tries to access previous app's class list when switching apps from AppsMenu in the Sidebar.

### Steps to reproduce

- have multiple apps with atleast one unique className in all three apps.
- Select another app from AppsMenu in the Sidebar

https://github.com/parse-community/parse-dashboard/assets/44117648/795a65c0-2592-4769-bd55-6fc1bd130323

### Actual Outcome

Blank browser dashboard page, as it was trying to fetch data for the class that does not exists in the App.

### Expected Outcome

Properly redirected to first class in the app and not show blank page.

### Environment

Dashboard
- Parse Dashboard version: `5.3.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 120.0.6099.129 (Official Build) (arm64)`

Server
- Parse Server version: `5.2.3 `
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB - 3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote`

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Closes: #2519 

### Approach
The existing "remembering last location feature"(#2458) doesn't work for switching between apps, leading to a bug. Therefore, I've enhanced the feature to include this scenario as well.

### CODE REVIEW

**Comment by patelmilanun** [comment]
LGTM!

**Review by patelmilanun — APPROVED** [review]
LGTM!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
