### PR TITLE
refactor: replace create-react-class with ES6 classes

### PR DESCRIPTION
**Pull request by visualfanatic**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Rest of the app uses ES6 classes, the last of two components that were using `create-react-class` can be safely refactored to "native" class components.

### TODOs before merging

- [x] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by dblythy** [comment]
Nice refactor! Can you commit `package-lock` as well?

**Comment by visualfanatic** [comment]
@dblythy `package-lock` was not updated by `npm`, because this exact version of `create-react-class` is being used by other package.

**Comment by mtrezza** [comment]
Is this ready for review?

**Comment by visualfanatic** [comment]
@mtrezza yes

**Review by mtrezza — APPROVED** [review]
Looks good! Thanks for making Parse Dashboard 1 dependency lighter.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.2.0)

**Pull request merged**
