### PR TITLE
feat: apply filter in data browser by pressing "Enter" key

### LINKED ISSUE #2051: Applying filters with 'Enter' Keys
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Applying filters is currently only possible by clicking the "Apply these filters" button with the mouse.

image

### Feature / Enhancement Description
After filling in filter settings it would be cool if you could simply apply the filters either by pressing the normal "Enter" button or the "Enter" button in the numpad.

### Example Use Case
Sometimes I use many filters, it would be a lot easier if you could apply filters with the enter keys.

### Alternatives / Workarounds
Currently you have to apply filters by clicking the "Apply these filters" button with the mouse.

### 3rd Party References
It's the standard for confirming / applying nearly every action you perform in browsers, apps, whatever.

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #2051

### Approach

If enter is pressed, then search for filters

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
