### PR TITLE
ci: Add deployment preview to pull requests via Uffizzi integration

### LINKED ISSUE #2374: Add PR deployment preview
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Reviewing a dashboard PR requires more effort than PRs from other repos because 
- Parse Dashboard is a visual product with UI
- We don't have UI testing as part of the CI

The dashboard PR has to be cloned locally in a development environment to see the effect of most PRs.

### Feature / Enhancement Description

Add a preview deployment to easily review and preview PRs online without having to clone the PR locally.

See https://docs.uffizzi.com/references/uffizzi-ci/#2-install-authorize-the-uffizzi-github-app

### Example Use Case

n/a

### Alternatives / Workarounds

Clone locally.

### 3rd Party References
n/a

### Uffizzi Feedback

- There seems to be an URL issue, see https://github.com/parse-community/parse-dashboard/pull/2370#issuecomment-1406928232:
  > https://https://app.uffizzi.com/projects/5259/deployments

- It would be nice to have all files in a `.uffizzi` directory. Currently we have:
  ```sh
  ./docker-compose.uffizzi.yml
  ./nginx-uffizzi/...
  ```

- When Uffizzi adds a comment it should probably delete any existing Uffizzi comments, otherwise the thread gets full of comments, and these comments are quite long. 

- While deploying a new commit, the preview URL shows an nginx error page; it's unclear whether the deployment / PR has an issue; it would be better to show a "deployment is progress" page
image

### PR DESCRIPTION
**Pull request by ShrutiC-git**
### New Pull Request Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Approach

This PR is opened as an update to PR #2352. This PR is moving `Uffizzi build` and `Uffizzi preview` workloads from GitHub actions to Uffizzi CI. 

Uffizzi CI will handle building the containers and provisioning preview environments for PRs. Once the preview is up and ready, a comment will be posted on the PR on GitHub. This requires lesser configuration than GHA integration. 

[Here is a guide](https://docs.uffizzi.com/references/uffizzi-ci/) on the Uffizzi CI setup and how it works.

Post merging this PR into Parse's `default` branch, you'll have to follow [these steps](https://docs.uffizzi.com/references/uffizzi-ci/#setting-up-uffizzi-ci) to configure Uffizzi CI to provision previews for PRs on Parse-dashboard.

Here is a [test PR](https://github.com/ShrutiC-git/parse-dashboard/pull/31) which was opened in my fork of Parse-dashboard. The building and provisioning were done outside of GHA and in Uffizzi CI. Post completion, [this comment](https://github.com/ShrutiC-git/parse-dashboard/pull/31#issuecomment-1405225133) was posted on the PR. This is the [preview environment](https://pr-31-deployment-12409-parse-dashboard.app.uffizzi.com/). To log into Parse-dashboard for this test PR, use the following credentials:
* username: admin
* password: password

cc @mtrezza

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
The integration looks much more lightweight now, thanks for the new PR. What's the status of this PR and what would we need to do to add this preview to all PRs of the Parse Dashboard repo? I think we could give this a try.

**Comment by ShrutiC-git** [comment]
that's great to hear — I'm glad we could align it to meet Parse's requirements :)

- You can start by merging this PR. 

- Post that, you'll need to sign up into Uffizzi.com with GitHub.

- After successful login, you could go through [these steps](https://docs.uffizzi.com/references/uffizzi-ci/#setting-up-uffizzi-ci) to setup Uffizzi CI

And you'll be good to go! 


Also, this is how the Uffizzi CI works for now.
> Currently Uffizzi CI will only create previews for pull requests that target the branch you configure in the Uffizzi Dashboard (Project > Settings > Compose file > Branch > Path to Compose). 
> 
> For example, if you configure Uffizzi CI with a Compose file from your main branch, Uffizzi will apply the following logic:
> Previews will be triggered for pull requests matching: 
> 
> main ← {topic_branch}
> Previews will not be triggered for pull requests matching: 
> 
> {topic_branch} ← main or 
> {topic_branch} ← {topic_branch}

Here are our docs on [how to use Uffizzi CI](https://docs.uffizzi.com/references/uffizzi-ci/#setting-up-uffizzi-ci) if you want to read more about this.

**Comment by mtrezza** [comment]
I assume we need to write our own bot to add the preview URL as a comment to the PR thread? Or is that a feature that is already supported?

> Post that, you'll need to sign up into Uffizzi.com with GitHub.

I tried that, but got an error:

image

The repository belongs to an org, but the org account `parse-community` cannot be used to sign in. Instead, we use another GitHub user `parseplatformorg` who has access to that org's repositories. When I sign up on Uffizzi with the GitHub account `parseplatformorg` and then choose "Configure GitHub" I don't see any repositories in the Uffizzi dashboard, because that account doesn't own any. If I choose "Configure GitHub" with the `parse-community` account that owns the repository Uffizzi shows the error above.

**Comment by gadkins** [comment]
Hi @mtrezza I'm co-founder at Uffizzi. Happy to help you out.

> I assume we need to write our own bot to add the preview URL as a comment to the PR thread? Or is that a feature that is already supported?

No you don't need to write your own bot, Uffizzi CI will post the comment for you. You will grant permission to the Uffizzi GitHub App to write to PR issues, as described [here](https://docs.uffizzi.com/references/uffizzi-ci/#2-install-authorize-the-uffizzi-github-app).  

It looks like [`parseplatformorg`](https://github.com/parseplatformorg) is technically a [GitHub Personal Account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#personal-accounts), which I assume has Owner role for the `parse-community` [Organizational Account](https://docs.github.com/en/get-started/learning-about-github/types-of-github-accounts#organization-accounts)? If that is the case, you should login to Uffizzi as `parseplatformorg` (Personal), and then create a Uffizzi Team for `parse-community` (Organizational). Once the `parse-community` Team is created, you can switch to this context and connect the credentials.  

Screen Shot 2023-01-27 at 11 33 52 AM
Screen Shot 2023-01-27 at 11 34 46 AM

**Review by mtrezza — APPROVED** [review]
Thanks, it found the repository; I'll merge this to continue the configuration in the console.
Continuing discussion in issue #2374.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.7](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
