### PR TITLE
feat: Reopen last opened class when navigating to data browser

### LINKED ISSUE #2458: Remember last opened class is data browser
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When navigating away from the data browser and the back to it, an empty page is displayed before a class is selected. This is a new, recent behavior, but the previous one was also not ideal, which just opened the first class, i.e. `_Installation`.

### Feature / Enhancement Description

Remember the last opened class in data browser and re-open it when navigating back to the data browser.

### Example Use Case

1. In data browser, open class `_User`.
2. In nav bar, click on "Web Hooks".
3. In nav bar, click on "Data Browser".
4. The `_User` class should be automatically opened, maybe even with the last used filter.

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

Closes: #2458 

### Approach

Storing data in localStorage and retrieving it upon rendering is a straightforward approach. However, if you prefer an alternative method, such as saving the data to state in withRouter, please let me know.

### CODE REVIEW

**Comment by mtrezza** [comment]
> Storing data in localStorage and retrieving it upon rendering is a straightforward approach. 

I think that's a good solution; so even if the browser is closed and the reopened, the last opened class will display?

**Comment by mtrezza** [comment]
> Storing data in localStorage and retrieving it upon rendering is a straightforward approach. 

I think that's a good solution; so even if the browser is closed and then reopened, the last opened class will display?

@patelmilanun what do you think?

**Comment by AshishBarvaliya** [comment]
Yes, I am storing the whole pathname with Search string, so it would show the filters also.

**Comment by mtrezza** [comment]
Great!

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.16](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.16)

**Comment by mtrezza** [comment]
@AshishBarvaliya You've been quite active recently in this repository. Would you be interested to join the Parse Dashboard team? You'd for example get notifications on mentions of `@parse-community/dashboard` to discuss issues.

**Comment by AshishBarvaliya** [comment]
@mtrezza yes for sure, would like to join the team. We'll make the dashboard better with latest tech and features so it would attract more contributors and become popular among users.

**Comment by mtrezza** [comment]
Amazing to hear that, let me send you an invite!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
