### PR TITLE
Release notes 1.3.0

### LINKED ISSUE #1037: Any reason for no recent releases?
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
Hi all,
Looks like its been more than a year since 1.2.0(released Mar 6, 2018), but no recent releases added to npm since then.

Its odd to me that the dashbaord is still actively being maintained, but no recent releases.
I'm trying to build from master for the dev option, but having lots of issues.

I'd much rather just 'npm i' the latest release..

#### Logs/Trace

[parse-dashboard]# sudo npm run build

> parse-dashboard@1.2.0 build /usr/share/node/my-parse-server/node_modules/parse-dashboard
> NODE_ENV=production webpack --config webpack/production.config.js && webpack --config webpack/PIG.config.js

(node:11011) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 1ae32fa202571224b31b
Version: webpack 4.29.6
Time: 593ms
Built at: 2019-03-27 13:30:47
 4 assets
Entrypoint dashboard = dashboard.bundle.js
Entrypoint login = login.bundle.js
Entrypoint PIG = PIG.bundle.js
Entrypoint quickstart = quickstart.bundle.js
 [2] ./parse-interface-guide/routes.js 248 bytes {0} [built] [failed] [1 error]
 [3] ./dashboard/index.js 273 bytes {1} [built] [failed] [1 error]
 [4] ./login/index.js 267 bytes {2} [built] [failed] [1 error]
 [5] ./parse-interface-guide/index.js 352 bytes {0} [built]
[12] ./quickstart/index.js 238 bytes {3} [built] [failed] [1 error]
    + 8 hidden modules

ERROR in ./parse-interface-guide/routes.js 15:0
Module parse failed: Unexpected token (15:0)
You may need an appropriate loader to handle this file type.
| 
| module.exports = (
> <Router history={history}>
|   <div>
|     <Route path='/:component?' render={(props) => {
 @ ./parse-interface-guide/index.js 10:0-30 14:16-22

### PR DESCRIPTION
**Pull request by acinader**
I merged in all of the open version bumps that worked 

I tried to do npm audit fix, but it errored

Not sure its worth doing a release, but I did test this a bit and it appears to work fine.

fixes #1037

### CODE REVIEW

**Comment by dplewis** [comment]
@acinader I updated the changelog. I really like the thank you portion of it. Should bring it back in other repos.

Don't forget the package-lock.json update.

A lot of changes in this one!

**Comment by acinader** [comment]
I agree that doing the thank you's is nice.  would be good to script generating the changes!

ideally, we want to get to a point where any merge that goes into master gets automatically pushed as soon as the tests pass, in which case the quaint old release notes go away and one would have to use git to see what is going on.  but i do like it.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.10](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
