### PR TITLE
fix: Cannot navigate to nested relation field in data browser

### LINKED ISSUE #2088: Cannot route to nested relations
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The routing to view relations is incorrect if you try to view them from another list of relations. 
### Steps to reproduce

On a class with a relation, select "View Relation" on a relation of classes that also has relations. In this list of relations, try to select "View Relation" again. 

### Actual Outcome

Clicking the first "View Relation" gives us the route of the format /browser/Class1/class1objectID/Class2Relation.
Clicking the second "View Relation" on the class2 object gives us the route of format /browser/Class1/class2objectID/Class3Relation
### Expected Outcome

Clicking the second "View Relation" on the class2 object should give us the route of format /browser/Class2/class2objectID/Class3Relation instead. 
### Environment

Dashboard
- Parse Dashboard version: `4.1.1-alpha.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Edge`
- Browser version: `100.0.1185.29`

Server
- Parse Server version: `4.2.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

parent class name is not updated on url

Closes: #2088

### Approach

using 'relation.parent.className' instead of 'this.props.params.className'

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
