### PR TITLE
fix: raw value of read-only date field in data browser cannot be copied

### LINKED ISSUE #1772: Remove tooltip for read-only date field
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

PR https://github.com/parse-community/parse-dashboard/pull/1688 introduces a change that shows a tooltip when trying to select the date string of a read-only date field (`updatedAt`, `createdAt`).

This is unusual because:

- It is contrary to how read-only spreadsheet or table cell elements work (allow to select, but in different visual state).
- It is contrary to how editable date fields can be interacted with, interfering with intuitive usability and work flow.
- It prevents the user from selecting and copying only a part of the date string.
- A tooltip is an intrusive UI element that should only be used if important information is displayed; in this case, it contains a description that the ctrl-c shortcut can be used copy a value.

### Steps to reproduce
1. Open any class in browser
2. Double click on `createdAt` read-only date field

### Actual Outcome
Shows tooltip.

### Expected Outcome

If a cell is read only, a cell or text field is usually displayed in a different visual style, still allowing the text to be selected but not edited.

Common UI design practice is to remove the "focus" indicator (ie. the element that highlights a selected cell). Given the existing design of Parse Dashboard, I suggest to just slightly gray out the background of the cell to make clear that it is non-editable.

image
(https://uxframework.pearson.com/c/inputs#states)

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `14.1.2`

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

### PR DESCRIPTION
**Pull request by mtrezza**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/1772).

### Issue Description

Related issue: #1772 
Closes: #1772 

### Approach

Removed tooltip for readonly fields
Update styles for Editor to show disabled state

Disabled Editor styles
image

Disabled Editor selected text
image

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
