### PR TITLE
Added tooltip for readonly fields

### PR DESCRIPTION
**Pull request by sadakchap**
Added a tooltip for readOnly fields.
Showing tooltip on doubleClick event.
Screenshot from 2021-04-21 16-03-06

### CODE REVIEW

**Review by davimacedo — APPROVED** [review]
LGTM!

**Review by davimacedo — CHANGES_REQUESTED** [review]
Actually, the tests are failing. Could you please check it out?

**Comment by sadakchap** [comment]
Yes, `npm run ci` was failing as I did added a dependency but did not committed `package-lock.json` file. 
I just added it now, please have a look.

**Review by davimacedo — APPROVED** [review]
LGTM!

**Comment by mtrezza** [comment]
This pop-up and selection restriction is a rather unintuitive UI behavior. I am not aware of any spreadsheet or table UI element that works that way.

If a cell is read only, then the text field can be set as disabled, which makes it selectable but not editable. It seems quite intrusive to prevent the user from selecting the date string in that field. It also prevents a user from double clicking into a date field and selecting only a part of the date. 

Should we revert this pop-up?

image

**Comment by sadakchap** [comment]
> This pop-up and selection restriction is a rather unintuitive UI behavior. 

Agree.

> If a cell is read only, then the text field can be set as disabled, which makes it selectable but not editable. It seems quite intrusive to prevent the user from selecting the date string in that field because it also prevents from selecting and copying only a part of the date string or scrolling the text left / right if the column is narrow.

For copying date string, user can still do `ctrl+c` after selecting the field.


> Should we revert this pop-up and instead simply make the field non-editable?

Yes, we can do that. But, then how would the user know why Editor is disabled as we will not be explicitly telling the user that this field is actually read-only ? Do you believe that this will be intuitive?

**Comment by mtrezza** [comment]
> Yes, we can do that. But, then how would the user know why Editor is disabled as we will not be explicitly telling the user that this field is actually read-only ? Do you believe that this will be intuitive?

Common UI design practice is to slightly gray out the field to indicate that it cannot be edited but is still selectable. Here is an example from the [Google Material Design](https://material.io/components/text-fields#filled-text-field) framework:
image

**Comment by mtrezza** [comment]
I have opened https://github.com/parse-community/parse-dashboard/issues/1772 to revert this.

**Pull request merged**
