### PR TITLE
Add distinct / unique filter

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/parse-community/parse-dashboard/issues/888

I don't really know the conventions for react, so any help would be appreciated.

screen shot 2018-10-26 at 2 25 03 pm

More testing will be needed as I may have missed something.

### CODE REVIEW

**Comment by dplewis** [comment]
@flovilmart Quick update

Add / Delete rows are disabled if filtering by unique.

All fields are readonly

It works for all fields except arrays. Discussed here https://github.com/parse-community/parse-server/pull/4195#issuecomment-331300980

I could use aggregate to make array work.

I could also add not unique filter, discussed here https://github.com/parse-community/parse-server/issues/5019

This haven't been tested on Postgres

**Comment by flovilmart** [comment]
Can you quickly test over on Postgres? Worst case add a flag on parse server features

**Comment by dplewis** [comment]
@flovilmart A quick fix for PG and everything works

**Comment by flovilmart** [comment]
@natanrolnik what do you think? Not well versed in this area ;)

**Comment by natanrolnik** [comment]
@flovilmart sorry the late reply.
Although react is also not my strongest skill, the changes look fine to me.
@dplewis would you mind adding a few more screenshot?

**Comment by dplewis** [comment]
@natanrolnik What would you like to see?

**Comment by dplewis** [comment]
Date

screen shot 2018-11-01 at 10 19 22 am

Object

screen shot 2018-11-01 at 10 19 07 am

Pointer

screen shot 2018-11-01 at 10 18 42 am

screen shot 2018-11-01 at 10 18 49 am

**Comment by natanrolnik** [comment]
Looks good. My only comment:

From what I see here, the “Add a column” button is still enabled. Do you think it makes sense to disable it? I think it does.

**Comment by dplewis** [comment]
Distinct queries don't have filtering fyi

screen shot 2018-11-01 at 1 46 04 pm

**Comment by dplewis** [comment]
@natanrolnik @flovilmart I just tried this against a Collection with 305k unique records and received a 504 (Gateway Timeout).

**Comment by acinader** [comment]
@dplewis what do you want to wit this?

**Comment by dplewis** [comment]
@acinader Waiting for review. I did find that on large datasets this can cause a timeout, if you haven't set timeout / index the field.

**Comment by acinader** [comment]
what do you think about that?

**Comment by dplewis** [comment]
A popup box with a warning or wait until indexes get added to dashboard

**Comment by acinader** [comment]
can you catch the timeout?

**Comment by dplewis** [comment]
After updating my server config maxTimeMS I don't get that timeout error.

**Pull request merged**
