### PR TITLE
refactor: remove file-loader and use asset modules instead

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
A small refactor that replaces `file-loader` with the built-in [asset module](https://webpack.js.org/guides/asset-modules/) available in webpack 5.

Related issue: #1855

### Approach
Removed old `file-loader` and replaced it with asset module.

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
Nice! please let me know when this is ready for review, I think you cannot request a review in the UI yet. And could you please remove the TODOs in the template that do not apply to the PR? So we know whether this is good to go.

**Comment by damianstasik** [comment]
@mtrezza thanks! It is ready for review, just have one question about the PR template: is there anything missing from it or the bot is just looking for those removed checkboxes?

**Comment by mtrezza** [comment]
The bot is complaining about not using the template when delete one or more headings that are in the template. I suggest you keep all headings as they are and just fill out "n/a" is a heading doesn't apply. We will simplify the templates soon.

**Comment by damianstasik** [comment]
@mtrezza somehow the first heading got lost, I added it back, but the bot does not like removed checkboxes at the top so I added back the second checkbox with a link to the PR and now it is fine.

**Comment by mtrezza** [comment]
Well done. Obviously, filling out a template is somewhat tedious, but if 1 author spends 10 seconds more on filling it out, it saves each future reader minutes of time to grasp the issue. It also helps reviewers to faster assess the issue and comment on it, which helps to prevent issues from getting stale.

**Review by mtrezza — APPROVED** [review]
Looks good! You are the king of package slimmers!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
