### PR TITLE
feat: Select rows in data browser by clicking and dragging mouse cursor over checkboxes

### LINKED ISSUE #2546: Select rows by pressing and dragging cursor over checkboxes
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When selecting rows, each checkbox requires a separate click. This is tedious when streaks of adjacent rows need to be selected.

### Feature / Enhancement Description

Select multiple adjacent rows by clicking in one checkbox, hold the mouse key and drag the mouse cursor down. All checkboxes underneath the drag path of the cursor should change to the state of the first checkbox. That means, if the first checkbox changed from unselected to selected, the all dragged-over checkboxes should end up being selected as well.

### Alternatives / Workarounds

Status quo, where each checkbox needs to be clicked individually.

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
Select rows by pressing and dragging cursor over checkboxes

Closes: #2546 

### Approach
Implemented the feature by simply using the `mousedown`, `mouseup`, and `mouseover` events on the checkbox tag.

### CODE REVIEW

**Comment by mtrezza** [comment]
I'm surprised there is no preview environment. Let's see how long this takes, or whether it's a bug.

**Comment by mtrezza** [comment]
Very nicely done! Just one more thing if you don't mind: could you make the whole cell with the checkbox clickable, instead of only the checkbox? Because the checkbox itself is quite small and a click in the rest of the cell around the checkbox doesn't do anything, so we have a lot of unused space. That would greatly improve usability when selecting a row.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)

**Pull request merged**
