### PR TITLE
feat: add config option `columnPreference.filterSortToTop` to set column name order in filter dialog

### LINKED ISSUE #1883: feature request: custom order of columns in the filter popup
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

We have some classes with a lot of columns. If we want to filter one of these classes, we use most of the time something like `email`, `objectId` or `userId`. If we open the filter popup we have to scroll down the entire list and search the correct column name.

### Feature / Enhancement Description

It would be really cool if there's a feature to change the order to our preferences. The `columnPreference` could be extended for this feature.

### Example Use Case

Add to the `columnPreference` a Boolean like `filterSortToTop`. Everything that is truthy will be on the top of the list.

### PR DESCRIPTION
**Pull request by vince1995**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Related issue: #1883 

### Approach

Every  column that is marked with `filterSortToTop` in the `columnPreference` setting will be sorted to the top of the filter popup.

This would sort `objectId` to the top of the list in the `_User` class.

```
"columnPreference": {
  "_User": [
    {
      "name": "objectId",
      "filterSortToTop": true
    },
    {
      "name": "updatedAt",
    }
  ]
}
```

image

### TODOs before merging

- [ ] Add tests
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

closes #1883

### CODE REVIEW

**Comment by mtrezza** [comment]
Kindly let me know when this is ready for review

**Comment by vince1995** [comment]
Adjusted the readme, ready for review. :) @mtrezza

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
