### PR TITLE
refactor: Remove warnings in Docker build

### LINKED ISSUE #2351: Docker image doesn't conform to best practices
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

### Feature / Enhancement Description

Conform to best practices.

### Example Use Case

Create an image from this image.

### Alternatives / Workarounds

Use bloated image as is.

### 3rd Party References

Noted in limitation links.

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

I've made similar fixes on the server: https://github.com/parse-community/parse-server/pull/8359

Closes: #2351 

### Approach

Follow the best practices linked above to properly build the image in stages. This PR has no breaking changes.

For example, when installing packages, [alpine docs](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache) and [docker docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds)(uses `git` in example code like parse-server) state to use `--no-cache`.

Lastly, the current image uses `--production` where it should use `--omit=dev` resulting in additional warnings being thrown in the docker build. This is discussed on [stackoverflow](https://stackoverflow.com/a/9276112/4639041).

### TODOs before merging

- [x] Verify image builds and runs

### CODE REVIEW

**Comment by cbaker6** [comment]
This PR is ready for review

**Review by mtrezza — COMMENTED** [review]
Thanks for the PR. The PR title is rather vague for a changelog entry. If this only removes warnings but has no other effect for the developer, how about something like:

> refactor: Remove warnings in Docker build

If there is another more specific title even better.

**Review by mtrezza — APPROVED** [review]
Looks good; waiting for CI to pass

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
