### PR TITLE
fix table scrolling

### PR DESCRIPTION
**Pull request by JacerOmri**
fixes https://github.com/ParsePlatform/parse-dashboard/issues/668

### CODE REVIEW

**Comment by ProximalPod** [comment]
Does not fix the issue for me

**Comment by mignev** [comment]
This PR works for us: https://github.com/ParsePlatform/parse-dashboard/pull/676

**Comment by kangaroo5383** [comment]
Any reason why this isn't being merged in? Seems like a low risk change and helps a bunch of folks.

**Comment by flovilmart** [comment]
Tested on safari and Chrome, looking good!

**Pull request merged**
