### PR TITLE
add @babel/runtime-corejs3

### PR DESCRIPTION
**Pull request by acinader**
get the build working again.

fixes: #1352

### CODE REVIEW

**Comment by acinader** [comment]
oops.  need to move @babel/runtime-corejs3 to dev-dependencies.  one min.

**Comment by acinader** [comment]
ok, now I think it's all ready :).

**Comment by dplewis** [comment]
@acinader corejs3 already exists in the package-lock.json file but it is labeled as a dev dependency

https://github.com/parse-community/parse-dashboard/blob/master/package-lock.json#L1061

The JS SDK has it as a main dependency.

https://github.com/parse-community/Parse-SDK-JS/blob/master/package.json#L33

To fix this you should delete the existing package-lock.json file and `npm install` and upload the new one. You should see that it is no longer a dev-dependency in the package-lock.json.

Greenkeeper only updated parse to 2.8.0 but not its dependencies.

**Comment by dplewis** [comment]
@acinader Here is the culprit (From Travis)

Screen Shot 2019-10-24 at 12 41 25 PM

Greenkeeper should have uploaded the correct package-lock file. Can you look into it?

**Comment by acinader** [comment]
It worked for me.    I also updated the changelog to get rid of a duplicate 2.0.5 entry and to give you the well-deserved credit for this.

One thing to note is that when I ran npm install, it changed the package-lock file (which I committed),  I'm assuming that this is because we grab the latest parse-server which may change the dependencies.

If this all looks good to you, just approve and i'll merge and publish.

thanks!!!

**Pull request closed without merging**
