### PR TITLE
refactor: use object refs instead of deprecated string refs

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
String refs are deprecated and React team will be removing them at some point in the future. This PR refactors them into object refs using `createRef`.

Related issue: #1866

### Approach
- Initialize empty refs in components' constructors using `React.createRef`,
- Replace `this.refs` object with class properties,
- Remove `ReactDOM.findDOMNode` for refs as they are unnecessary, as the ref already points to a DOM node,
- Replace string refs with references to the class properties

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! Another modernization step into the future!

**Comment by mtrezza** [comment]
@visualfanatic I thought you requested a review for this PR, but I just saw you didn't, was this ready for merge? It worked fine for me locally.

**Comment by damianstasik** [comment]
@mtrezza no worries, it was ready 👍

**Comment by mtrezza** [comment]
Good! Would you be interested in become a Parse Dashboard team member? You have made great contributions and you can also request reviews for a PR, which I think is currently disabled for you.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
