### PR TITLE
fix: Vertical scrollbar in data browser is outside visible area when scrolling horizontally

### LINKED ISSUE #2045: Vertical scrollbar is shown inside the horizontally scrollable area, which makes it usually out of sight
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

To see the vertical scrollbar, one has to scroll to the far right of the table, not on the screen, because many tables have many columns, and by going there, one no longer sees whatever horizontal position they were at, and in very wide tables, it may take a while to go back to the spot they were originally at, before looking at the scrollbar. Parse Dashboard is the only app I know that does this (among the ones kind enough to display a scrollbar).

### Steps to reproduce

Open any table where columns take more than one screen wide, in any version of Parse Dashboard.

### Actual Outcome

Vertical scrollbar only appears when horizontal scrollbar at maximum position (right end).

### Expected Outcome

Vertical scrollbar always visible.

### Environment

Dashboard
- Parse Dashboard version: both 2.1.0 release and in 4.0.0 release.
- Browser (Safari, Chrome, Firefox, Edge, etc.): Firefox
- Browser version: 97 and several previous ones

Server
- Parse Server version: 4.3.0
- Operating system: Heroku 18
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): Mongo
- Database version: ?
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Heroku

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

Closes: #2045 

### Approach

 Made minor adjustments to the width and overflow properties.

### CODE REVIEW

**Comment by mtrezza** [comment]
This causes the title bar not to scroll with the content

https://github.com/parse-community/parse-dashboard/assets/5673677/8a50aabf-c46f-4971-b755-8f362f9c1a1e

**Comment by AshishBarvaliya** [comment]
Ready to review.

Set position of header to sticky, it should work fine now.

**Review by mtrezza — APPROVED** [review]
Looks good and works in preview.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.15](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.15)

**Comment by mtrezza** [comment]
This PR ~likely~ introduced the bug https://github.com/parse-community/parse-dashboard/issues/2475; @AshishBarvaliya could you take a look and submit another PR? I've reverted the commit of this PR and re-opened the issue.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
