### PR TITLE
feat: Sort Cloud Code Jobs alphabetically

### LINKED ISSUE #2394: Jobs list is in random order - would be nice to be sorted
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
The jobs list (Jobs -> All Jobs) is showing in apparently random order. It would make finding jobs easier to have it show them in either alphabetical order, or order they are defined in the jobs.js file. [The latter behaviour is what I see on the Back4App version of the Dashboard - not sure if they have customised it or run an old version]

### Feature / Enhancement Description
Either sort by default the jobs into a known order, or let a click on the 'Name' column header sort them into alphabetical order.

### Example Use Case
I have a large number of jobs in my cloud code base - finding one to run while developing is harder than it should be due to a seemingly random order.

### 3rd Party References
Back4App version of parse dashboard lists the jobs in order of definition from the source file, not as good as alphabetical but better than random.

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-dashboard/issues/2394

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
