### PR TITLE
feat: Data types and pointer classes are sorted alphabetically in dialog to add new column

### LINKED ISSUE #1234: When creating a new Pointer field, classes are in arbitrary order
When adding a new Column of type `Pointer`, the dropdown menu for Target Class is in some inscrutable order, should be alphabetical, or at least predictable.

Screen Shot 2019-08-21 at 12 36 40

Parse Server 3.0, Parse Dashboard 1.3.3

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Closes: https://github.com/parse-community/parse-dashboard/issues/1234

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
