### PR TITLE
refactor: update webpack-cli to latest version

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR updates `webpack-cli` to the latest version. Since `4.1.0` there were many great changes like:

- fix for the deprecation warning:
```
(node:21861) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument needs to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
- colored output:

<table>
<tr>
<td>Screen Shot 2021-10-31 at 13 20 22</td>
<td>Screen Shot 2021-10-31 at 13 21 16</td>
</table>

- new option `--node-env` to set `NODE_ENV` with `webpack-cli`, no need to use `cross-env`
- [fixed watch mode](https://github.com/webpack/webpack-cli/issues/1923)

I tested `build` command and development mode, everything works as expected.

Related issue: #1902

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@visualfanatic Could you please resolve the conflicts?

**Review by mtrezza — APPROVED** [review]
Looks good! Another deprecation warning less!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-alpha.15](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0)

**Pull request merged**
