### PR TITLE
fix: Blank screen shown if server is unreachable; unsupported pages are accessible via direct URLs

### LINKED ISSUE #1596: Parse Dashboard only showing a blank white page
_Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!_

- [✔] _You're running version >=1.0.23 of Parse Dashboard._

- [✔] _You're running version >=2.3.2 of Parse Server._

- [✔] _You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before._

I know this symptom has come up dozens of times, and I have gone through some dozen tickets and SO pages to try and resolve it. Nothing has worked for me so far.

#### Environment Setup
Docker

I am seeing this:
image

#### Steps to reproduce
I am following the steps in this Medium article: 
https://medium.com/@yildizberkay/how-to-install-parse-server-with-docker-c5931bd84c17

Which can be summarized as:
```
docker run --name parse-mongo-db \
-e MONGO_INITDB_ROOT_USERNAME=admin \
-e MONGO_INITDB_ROOT_PASSWORD=admin \
-d mongo

docker run --name parse-server-1 \
 -e PARSE_SERVER_APPLICATION_ID=APP_ID_1 \
 -e PARSE_SERVER_MASTER_KEY=MASTER_KEY_1 \
 -e PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin \
 --link parse-mongo-db:mongo \
 -d -p 1337:1337 parseplatform/parse-server

docker run --name parse-dashboard-1 \
 -e PARSE_DASHBOARD_APP_ID=APP_ID_1 \
 -e PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY_1 \
 -e PARSE_DASHBOARD_USER_ID=admin \
 -e PARSE_DASHBOARD_USER_PASSWORD=admin \
 -e PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true \
 -e PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse \
 -d -p 4040:4040 parseplatform/parse-dashboard
```

#### Logs/Trace

From the chrome console:
```
VM115:1 POST http://localhost:1337/serverInfo net::ERR_CONNECTION_REFUSED
VM115:1 POST http://localhost:1337/schemas net::ERR_CONNECTION_REFUSED
VM115:1 POST http://localhost:1337/schemas net::ERR_CONNECTION_REFUSED
VM115:1 POST http://localhost:1337/schemas net::ERR_CONNECTION_REFUSED
VM115:1 POST http://localhost:1337/schemas net::ERR_CONNECTION_REFUSED
VM115:1 POST http://localhost:1337/schemas net::ERR_CONNECTION_REFUSED
```

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Parse Dashboard currently displays a white screen if the server is unreachable, without showing any useful information. This PR changes this to:

Screenshot 2023-01-20 at 3 23 25 pm

Parse Dashboard also allows routing to unsupported legacy routes (by manually entering the URL), such as:

Screenshot 2023-01-20 at 3 22 02 pm

This PR adds a check to make sure the route is supported, and if not:

Screenshot 2023-01-20 at 3 23 53 pm

Closes: #1596

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)

**Pull request merged**
