### PR TITLE
fix: Avoid filter tab disappears on apply filter

### PR DESCRIPTION
**Pull request by alencarlucas**
ref #1140 

chrome-capture (1)

### CODE REVIEW

**Comment by davimacedo** [comment]
@mtrezza do you mind to give it a try and let us know if it solves the issue?

**Comment by mtrezza** [comment]
I’ll give it a shot.

**Comment by mtrezza** [comment]
I’ll check it out.

**Comment by davimacedo** [comment]
@alencarlucas I've tried it out and it seems working fine. I have just one additional question. Is it possible to dismiss the menu when clicking outside the box? Thanks!

**Comment by dplewis** [comment]
@alencarlucas if you want external click see 

https://github.com/parse-community/parse-dashboard/pull/1235/commits/517ae298863feea4849dd81397eb7fbae14a400a

**Comment by alencarlucas** [comment]
@davimacedo @dplewis Fixed.

**Pull request merged**
