### PR TITLE
fix: Scroll position is preserved when re-opening the same class in data browser via navigation bar

### LINKED ISSUE #2443: Scroll position is preserved when re-opening the same class in data browser via navigation bar
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Scroll position does not reset when a filter is active and clicking on the class in the data browser.

### Steps to reproduce

Prerequisites:
- `ClassA` needs to contain more data rows than can be displayed on 1 page in web browser, e.g. 3 pages full of rows.

1. Go to `ClassA` in data browser.
2. Set any filter.
3. Scroll down like half a page.
4. In the data browser class list on the left click on `ClassA`.

### Actual Outcome

The unfiltered table for `ClassA` is displayed with a scroll position that is down half a page.

### Expected Outcome

The unfiltered table for `ClassA` is displayed with a scroll position that is scrolled to the top.
This is also the current behavior when clicking on a class that is not the current class.

### Environment

Dashboard
- Parse Dashboard version: `5.1.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `Version 16.4 (18615.1.26.110.1)`

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

Closes: #2443 

### Approach

Ensure that the `scrollTop` is set to 0 whenever there are updates in the filters.

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, works in preview environment

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
