### PR TITLE
refactor: Sidebar collapse

### PR DESCRIPTION
**Pull request by douglasmuraoka**
Removes the old `SidebarToggle` component and allows users to collapse the sidebar even when window width is greater than 980px. Adds a `Pin` button that fixes the sidebar, avoiding any collapses.
Once collapsed, expands the sidebar when on mouse over, and collapses on mouse leave.

Collapsed:
image

Expanded:
image

Closes https://github.com/parse-community/parse-dashboard/issues/1759.

### CODE REVIEW

**Comment by davimacedo** [comment]
@douglasmuraoka thanks for working on this. Few questions:
- The arrow in the App Select stopped changing when the Select is opened/closed. Is it also possible to change its color to white?
- Is it possible to change the pin button color to white?
- Is it possible to have the pin button changed so the user can know if it is pinned or not?

**Comment by tehsunnliu** [comment]
Hi all, I've noticed this issue has not been merged. I was facing issues when using the parse-dashboard on a smaller screen.
The sidebar doesn't collapse and the table goes behind the sidebar hiding the columns behind it. I'm using parse release version 2.1.0.
dashboard-1
dashboard

Is there any chance of getting this fixed?
Thank you.

**Comment by tehsunnliu** [comment]
Please merge this. The dashboard sidebar needs a Fix. 
Or guide me to fix the Danger.

**Comment by mtrezza** [comment]
@tehsunnliu Thanks for bringing this to our attention. I think it just needs a rebase on master, then we can merge it. I'll look into that.

**Comment by mtrezza** [comment]
Continued in https://github.com/parse-community/parse-dashboard/pull/1760

**Comment by tehsunnliu** [comment]
Hi @mtrezza Thank you so much for initiating this. I'll check this out.

**Pull request closed without merging**
