### PR TITLE
feat: Add refresh button to Cloud Config page

### LINKED ISSUE #2479: Add refresh button to Cloud Config
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The Cloud Config page can only be refreshed with a browser refresh.

### Feature / Enhancement Description
Add refresh button to Cloud Config page, like on the Jobs page.

### PR DESCRIPTION
**Pull request by patelmilanun**
### New Pull Request Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
There is no refresh button for cloud config page.

Closes: #2479 

### Approach
Copy paste same functionality which is already there in Jobs page.

### TODOs before merging
NA

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, works in preview

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.22](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.22)

**Comment by mtrezza** [comment]
@patelmilanun You've been quite active recently in this repository. Would be interested to join the Parse Dashboard team? You'd for example get notifications on mentions of `@parse-community/dashboard` to discuss issues.

**Comment by patelmilanun** [comment]
@mtrezza Sure! why not

**Comment by mtrezza** [comment]
Amazing to hear that, let me send you an invite!

**Comment by patelmilanun** [comment]
Will this gonna add ?
image

**Comment by mtrezza** [comment]
Yes, the org will show in your GitHub profile.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by mtrezza** [comment]
I just realized that the refresh animation is on a fixed vertical position, so it can be outside the window. Only a blank table is visible then. After trying this out a bit more, it's definitely better than before, but on a network, or localhost, the page is reloaded so quickly that it's just a white flicker. Maybe it would be better to show a pop-up message at the bottom that is has been reloaded, so that it's visible for some time. And instead of removing the whole table I would just overlay it with a white layer and display the animation on top of it, so make it easier on the eye.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
