### PR TITLE
feat: Add parameter `selectedField` to script payload to determine which object field was selected when script was invoked

### LINKED ISSUE #2473: Pass selected field to Cloud Function script
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Currently, it cannot be determined which field was been selected when a script has been invoked.

### Feature / Enhancement Description

Pass the selected field as a separate parameter to the Cloud Function payload.

For example the dashboard user should be able to invoke a script on a user in a specific field of the selected object:
- Transaction class: buying user, selling user

Knowing only the "transaction" object is not enough to know on which user the Cloud Function should be executed.

### Example Use Case

```js
Parse.Cloud.define('deleteUser', async (req) => {
  const selectedTransaction = req.params.object;
  selectedTransaction.set('invalid', true);
  await selectedTransaction.set.save(null, { useMasterKey: true });

  const selectedUser = req.params.selectedField;
  if (selectedUser instanceof Parse.User) {
    selectedUser.set('deleted', true);
    await selectedUser.save(null, { useMasterKey: true });
  }
});
```

### Alternatives / Workarounds

None.

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Currently, the context of what field a script was invoked on is not passed.

Closes: #2473

### Approach

Sends `selectedField` to the cloud function

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.23](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.23)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
