### PR TITLE
refactor: update svgprep plugin for webpack 5

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR updates the SVG Prep plugin for webpack 5 as the current version throws the following warning:
```
(node:95614) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

Related issue: #1859

### Approach
1. The plugin now uses the recommended `processAssets` hook instead of `emit`.
2. Replaced `tapAsync` with `tapPromise` to simplify the code with `async`/`await`.
3. There is now an additional hook that wraps the previous one, it is required to have access to the current `compilation` process.
4. Replaced `!!name.match(/\.svg$/)` with `name.endsWith('.svg')` to make it easier to understand how the array is filtered.
5. Used `compilation.emitAsset` instead of just putting new objects into `compilation.assets` which was the old way (pre-webpack 5) of emitting new assets.
6. The emitted source is now wrapped with `RawSource` to let `webpack-sources` handle the final format (which usually is an object with `source` and `size` properties).

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
It builds fine, please again let me know when this is ready for review.

**Comment by damianstasik** [comment]
@mtrezza It is ready 👍

**Review by mtrezza — APPROVED** [review]
Looks good! Another annoying deprecation message less is candy for the eye!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
