### PR TITLE
fix: Option missing for Parse Config parameter to require master key

### LINKED ISSUE #2439: Missing config parameter option master key required
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

It's not possible anymore to set a config option as "master key required". The dialog originally contained such an option. At some point it got lost it seems.

See https://github.com/parse-community/parse-dashboard/pull/1233#issuecomment-523394095.

The current workaround is to go directly manipulate the option in the DB collection `_GlobalConfig`.

### Steps to reproduce

Config > Add new parameter

### Actual Outcome

No option to set parameter to require master key.

### Expected Outcome

Should have option as in screenshot in https://github.com/parse-community/parse-dashboard/pull/1233#issuecomment-523394095.

### Environment

Dashboard
- Parse Dashboard version: `5.1.0`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

MasterKey field is missing for config.

Closes: #2439

### Approach

Screenshot 2023-05-30 at 3 43 41 pm

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by mtrezza** [comment]
Oh so it was indeed just a dashboard issue, glad to see that 😮‍💨

**Review by mtrezza — APPROVED** [review]
Looks good, and works in preview deployment, is this ready for merge?

**Comment by dblythy** [comment]
Yep!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.10](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
