### PR TITLE
fix: calendar widget layout partly hides last days of a month

### LINKED ISSUE #1989: Calendar widget layout issue
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The calendar widget has a height set to it, which causes layout issue when the calendar is displaying a month with 31 days etc.
Captura de tela de 2022-01-07 11-51-41 (1)
CalendarWidget

### Steps to reproduce

1. In the Dashboard > Browser, navigate to a class that has a date type cell. 
2. Click on the cell to open the widget. 
3. Once the widget is open, scroll through months until you see the layout issue.

### Actual Outcome

The Calendar widget has layout issues where the action footer of the calendar sometimes overlaps with the dates.

### Expected Outcome

The Calendar widget should show the calendar action footer properly without overlapping with the dates.

Dashboard
- Parse Dashboard version: `latest`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `latest`
- Operating system: `wsl-ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongodb`
- Database version: `v3.6.3`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### PR DESCRIPTION
**Pull request by fn-faisal**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/1989).

### Issue Description

Fixed the calendar widget layout issue by setting the height to auto.

Related issue: https://github.com/parse-community/parse-dashboard/issues/1989

### Approach

The calendar should adapt to the inner div ( div that displays month dates ) height.

### TODOs before merging

- [ ] Add tests
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@fn-faisal ~~Thanks for this PR, could you please open an issue and add maybe a before / after screenshot to better describe the issue?~~ Added the issue reference.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.3](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.1)

**Pull request merged**
