### PR TITLE
fix: context menu in data browser is not scrollable

### LINKED ISSUE #2265: Context menu not scrollable
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

If a context menu is higher the the window height, it's not scrollable.

For example, if the list of related records is higher than the window height:

### Steps to reproduce
1. Open a long list of related records and resize browser window height to be smaller than the list height.

### Actual Outcome

List should be scrollable in some way (auto-scroll when on first / last visible entry, or via mouse -> mind how to use that on touch UIs)

### Expected Outcome

List is cut off.

### Environment

Dashboard
- Parse Dashboard version: `[4.2.0-alpha.11](https://github.com/ParsePlatform/parse-dashboard/compare/4.2.0-alpha.10...4.2.0-alpha.11)`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari, Chrome`

### PR DESCRIPTION
**Pull request by dblythy**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

If there are too many related records, they can show off screen.

Related issue: #2265
Closes: #2265

### Approach

Adds max height and overflow to context

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by dblythy** [comment]
Screen Shot 2022-09-17 at 11 26 05 pm

**Comment by mtrezza** [comment]
Does this work on touch UI? It's not a requirement, because there are UI elements in dashboard already that are not compatible with touch, but it would be nice to have.

**Comment by dblythy** [comment]
The context menu itself isn't compatible with touch UI as it requires a right click to show

**Review by mtrezza — COMMENTED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.15](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
