### PR TITLE
style: require new line at the end of file

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR adds a new rule to the ESLint config so that each file is required to end with a new line.

I also ran ESLint on all files just to make sure all files now end with a new line.

Related issue: #1870

### Approach
- Include the `eol-last` in the config file
- Run ESLint on all files

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by damianstasik** [comment]
Ready for review 👍

**Comment by mtrezza** [comment]
@visualfanatic You seem to be on an amazing PR streak today! Would you be interested in officially joining the Parse Dashboard team as a [contributor](https://github.com/parse-community/Governance#contributors)? This will also make it easier for you to request reviews using the GitHub feature in the top right corner that is disabled for non-members.

**Comment by damianstasik** [comment]
@mtrezza Thanks!

> Would you be interested in officially joining the Parse Dashboard team as a contributor?

I would love to!

**Comment by mtrezza** [comment]
Great, I have opened a [poll](https://community.parseplatform.org/t/vote-to-add-visualfanatic-as-a-member/2106) to formally propose your membership.

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.9](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)

**Pull request merged**
