### PR TITLE
fix: Back button in data browser disappears after page refresh

### LINKED ISSUE #2417: The back button disappears when I refresh the page.
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The back button disappears when I refresh the page on the _Role page.

### Steps to reproduce

1. Go to _Role
2. Click on "View Relation"
230930913-4bf1c2a1-bd82-448c-a3b8-1c50ed704e0a

3. You will see this page with back button.
Screenshot 2023-04-12 at 11 34 31 PM

4. Now refresh the page, You will see the same page without back button.
Screenshot 2023-04-12 at 11 37 47 PM

### Actual Outcome

The back button disappears when I refresh the page.

### Expected Outcome

The back button should remain visible.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

### PR DESCRIPTION
**Pull request by gtanchak**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description

Closes: #2417

### CODE REVIEW

**Review by AshishBarvaliya — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)

**Pull request merged**
