### PR TITLE
refactor: use new React context API

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR refactors the code that uses the legacy context API. 

Related issue: #1950

### Approach
- Look for all `contextTypes` properties and replace them with `contextType` class property
- Refactor `generatePath` to be a pure function
- Refactor `subscribeTo` HOC to be a functional component to have better control when context (current app) changes
- A few changes in some components to make them work with the new context API

### TODOs before merging

- [x] Fix issue with browser table not reloading when changing class
- [x] Refactor the code to use new context API
- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good, that's quite an amazing PR!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0-beta.1)

**Comment by 404-html** [comment]
Cześć @visualfanatic, QQ: do you have an idea what could go wrong here? https://github.com/parse-community/parse-dashboard/issues/1991

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.0.0)

**Pull request merged**
