### PR TITLE
fix: Adding a file when adding a new row in the data browser doesn't show filename

### LINKED ISSUE #2418: The uploaded file is not being displayed in the _Product class.
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The uploaded file is not being displayed in the default _Product class.

### Steps to reproduce

CPT2304132340-1068x670

### Actual Outcome

hidden file name

### Expected Outcome

It should show the file name just like for other classes.
Screenshot 2023-04-13 at 11 36 19 PM

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

Closes: #2418 

### Approach

showing filename without url.

### CODE REVIEW

**Comment by mtrezza** [comment]
Changed the PR title, as you [said](https://github.com/parse-community/parse-dashboard/issues/2418#issuecomment-1599683881):

> This issue is not confined to a specific class(_Product)

**Review by mtrezza — APPROVED** [review]
Looks good; tested locally

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.27](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.27)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
