### PR TITLE
feat: show skeleton as loading indicator in data browser while data is loading

### LINKED ISSUE #2272: Show data loading indicator
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
When navigating between classes data browser is wiped and it's no obvious that fetching the data is in progress. 

### Feature / Enhancement Description
It would be good to show that data is loading. Showing skeleton is a good pattern and a standard already.

### Example Use Case

https://www.freecodecamp.org/news/how-to-build-skeleton-screens-using-css-for-better-user-experience/

### Alternatives / Workarounds

Showing existing loader.

### 3rd Party References

Facebook, Google, etc.

### PR DESCRIPTION
**Pull request by Magdaraa**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues/2272).

### Issue Description
 

Closes: https://github.com/parse-community/parse-dashboard/issues/2272

### Approach

Showing absolute div with animated skeleton inside while data is loading.

data-browser-skeleton

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

Done with help from @404-html

### CODE REVIEW

**Review by mtrezza — APPROVED** [review]
Looks good! That's a nice one!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.14](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.14)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)

**Pull request merged**
