### PR TITLE
refactor: upgrade polyfill dependencies

### PR DESCRIPTION
**Pull request by damianstasik**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Issue Description
This PR upgrades `core-js` and `regenerator-runtime` deps to latest versions, but also removes `babel-plugin-syntax-object-rest-spread` and `@babel/polyfill` as it is not needed and is deprecated since `7.4.0`. I also moved `core-js` to regular dependencies as it is runtime code and moved imports of polyfill at the top of the entry so they are available as soon as possible.

Related issue: #1902

### TODOs before merging

- [x] A changelog entry is created automatically using the pull request title (do not manually add a changelog entry)

### CODE REVIEW

**Comment by mtrezza** [comment]
@visualfanatic what is missing to get this PR merged?

**Comment by damianstasik** [comment]
@mtrezza I just upgraded `core-js` to the latest version, now it should be ready to be merged.

**Review by mtrezza — APPROVED** [review]
Amazing! Thanks, let's merge.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.2-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.1.2-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.2-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.1.2-beta.1)

**Pull request merged**
