### PR TITLE
Allow external authInstance, fixes #751

### LINKED ISSUE #751: Since 1.0.20 it's impossible to use an external `passport` authentication
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
parse-dashboard 1.1.0

#### Steps to reproduce
We're using an external authentication (Google OAuth2 with passport), since the commit https://github.com/parse-community/parse-dashboard/commit/be9f498efe78211e6478ec9ce2d4e2cb959830d0 
it's impossible to use external `passport` strategy.
The easiest fix would be to allow an external `authInstance` key in `config` which will provide `authInstance.initialize(app)` method, and use it instead of the Authentication if provided.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

### PR DESCRIPTION
**Pull request by romanbsd**
Fixes https://github.com/parse-community/parse-dashboard/issues/751

### CODE REVIEW

**Comment by davimacedo** [comment]
Thanks for the PR. Could you please give an example on how that could be used or, even better, add the example in the repository readme?

**Comment by romanbsd** [comment]
Even better; I plan extracting our logic into a GoogleAuthenticator class. But that may take some time, since I have to switch to other things at the moment.

**Comment by mtrezza** [comment]
@romanbsd If this PR is still relevant, can you please add a changelog entry and add a README explanation to describe this new config option?

**Comment by mtrezza** [comment]
I'm closing this as it seems to lack essential information that is needed to further explore this issue. Feel free to comment if you can provide further details or have any questions and we can re-open this issue.

**Pull request closed without merging**
