### PR TITLE
refactor: upgrade core-js from 3.24.1 to 3.25.1

### PR DESCRIPTION
**Pull request by parseplatformorg**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade core-js from 3.24.1 to 3.25.1.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **2 versions** ahead of your current version.
- The recommended version was released **23 days ago**, on 2022-09-07.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>core-js</b></summary>
    <ul>
      <li>
        <b>3.25.1</b> - <a href="https://snyk.io/redirect/github/zloirock/core-js/releases/tag/v3.25.1">2022-09-07</a></br><ul>
<li>Added some fixes and workarounds of FF30- typed arrays bug that does not properly convert objects to numbers</li>
<li>Added <code>sideEffects</code> field to <code>core-js-pure</code> <code>package.json</code> for better tree shaking, <a href="https://snyk.io/redirect/github/zloirock/core-js/issues/1117" data-hovercard-type="issue" data-hovercard-url="/zloirock/core-js/issues/1117/hovercard">#1117</a></li>
<li>Dropped <code>semver</code> dependency from <code>core-js-compat</code>
<ul>
<li><code>semver</code> package (ironically) added <a href="https://snyk.io/redirect/github/npm/node-semver/commit/d61f828e64260a0a097f26210f5500">a breaking change and dropped NodeJS 8 support in the minor <code>7.1</code> version</a>, after that <code>semver</code> in <code>core-js-compat</code> was pinned to <code>7.0</code> since for avoiding breaking changes it should support NodeJS 8. However, since <code>core-js-compat</code> is usually used with other packages that use <code>semver</code> dependency, it causes multiple duplications of <code>semver</code> in dependencies. So I decided to remove <code>semver</code> dependency and replace it with a couple of simple helpers.</li>
</ul>
</li>
<li>Added Bun 0.1.6-0.1.11 compat data</li>
<li>Added Deno 1.25 compat data mapping</li>
<li>Updated Electron 21 compat data mapping</li>
<li>Some stylistic changes, minor fixes, and improvements</li>
</ul>
      </li>
      <li>
        <b>3.25.0</b> - <a href="https://snyk.io/redirect/github/zloirock/core-js/releases/tag/v3.25.0">2022-08-24</a></br><ul>
<li>Added <a href="https://tc39.es/ecma262/#sec-object.prototype.__proto__" rel="nofollow"><code>Object.prototype.__proto__</code></a> polyfill
<ul>
<li>It's optional, legacy, and in some cases (mainly because of developers' mistakes) can cause problems, but <a href="https://snyk.io/redirect/github/denoland/deno/issues/13321" data-hovercard-type="issue" data-hovercard-url="/denoland/deno/issues/13321/hovercard">some libraries depend on it</a>, and most code can't work without the proper libraries' ecosystem</li>
<li>Only for modern engines where this feature is missed (like Deno), it's not installed in IE10- since here we have no proper way setting of the prototype</li>
<li>Without fixes of early implementations where it's not an accessor since those fixes are impossible</li>
<li>Only for the global version</li>
</ul>
</li>
<li>Considering <code>document.all</code> as an object in some missed cases, see <a href="https://tc39.es/ecma262/#sec-IsHTMLDDA-internal-slot" rel="nofollow">ECMAScript Annex B 3.6</a></li>
<li>Avoiding unnecessary promise creation and validation result in <code>%WrapForValid(Async)IteratorPrototype%.return</code>, <a href="https://snyk.io/redirect/github/tc39/proposal-iterator-helpers/pull/215" data-hovercard-type="pull_request" data-hovercard-url="/tc39/proposal-iterator-helpers/pull/215/hovercard">proposal-iterator-helpers/215</a></li>
<li>Fixed omitting the result of proxing <code>.return</code> in <code>%IteratorHelperPrototype%.return</code>, <a href="https://snyk.io/redirect/github/zloirock/core-js/issues/1116" data-hovercard-type="issue" data-hovercard-url="/zloirock/core-js/issues/1116/hovercard">#1116</a></li>
<li>Fixed the order creation of properties of iteration result object of some iterators (<code>value</code> should be created before <code>done</code>)</li>
<li>Fixed some cases of Safari &lt; 13 bug - silent on non-writable array <code>.length</code> setting</li>
<li>Fixed <code>ArrayBuffer.length</code> in V8 ~ Chrome 27-</li>
<li>Relaxed condition of re-usage native <code>WeakMap</code> for internal states with multiple <code>core-js</code> copies</li>
<li>Availability cloning of <code>FileList</code> in the <code>structuredClone</code> polyfill extended to some more old engines versions</li>
<li>Some stylistic changes and minor fixes</li>
<li>Throwing a <code>TypeError</code> in <code>core-js-compat</code> / <code>core-js-builder</code> in case of passing invalid module names / filters for avoiding unexpected result, related to <a href="https://snyk.io/redirect/github/zloirock/core-js/issues/1115" data-hovercard-type="issue" data-hovercard-url="/zloirock/core-js/issues/1115/hovercard">#1115</a></li>
<li>Added missed NodeJS 13.2 to <code>esmodules</code> <code>core-js-compat</code> / <code>core-js-builder</code> target</li>
<li>Added Electron 21 compat data mapping</li>
<li>Added Oculus Browser 23.0 compat data mapping</li>
</ul>
      </li>
      <li>
        <b>3.24.1</b> - <a href="https://snyk.io/redirect/github/zloirock/core-js/releases/tag/v3.24.1">2022-07-29</a></br><ul>
<li>NodeJS is ignored in <code>IS_BROWSER</code> detection to avoid a false positive with <code>jsdom</code>, <a href="https://snyk.io/redirect/github/zloirock/core-js/issues/1110" data-hovercard-type="issue" data-hovercard-url="/zloirock/core-js/issues/1110/hovercard">#1110</a></li>
<li>Fixed detection of <code>@@ species</code> support in <code>Promise</code> in some old engines</li>
<li><code>{ Array, %TypedArray% }.prototype.{ findLast, findLastIndex }</code> marked as shipped <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1775026" rel="nofollow">in FF104</a></li>
<li>Added iOS Safari 15.6 compat data mapping</li>
<li>Fixed Opera 15 compat data mapping</li>
</ul>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/zloirock/core-js/releases">core-js GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>core-js</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/3c2e601b9a58af4dca0cd13aa943ab66b3deb83d">3c2e601</a> 3.25.1</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/60519bc872c2a9da99586b3d95f3f580637b30c1">60519bc</a> update the changelog</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/bb1de0f85086e944668a1f9050198728d25e5353">bb1de0f</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/2c1e73e1a20cbbac9f0141bedb8dd9d3ca6a9f3f">2c1e73e</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/ce987cb28a9f26bf889c663a023c62993ed7e0d0">ce987cb</a> improve some tests</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/6ca3e61ab973238285110edc1c5e37e96fbeb906">6ca3e61</a> fix some blocks</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/eb8ed332079673b77127b59201dd608cc6e1d329">eb8ed33</a> fix a typo</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/bacfb3ffc0f381ef81b8f4e17ef69762888c90b8">bacfb3f</a> add &quot;PRs welcome&quot; badge with a link to &#x60;CONTRIBUTING.md&#x60;</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/b534518abce134c915860c2a4528337f8d041dbf">b534518</a> just in case detect correctness of &#x60;globalThis&#x60;</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/79ababc6afcf6e112cdde081eadc06540bb36c2a">79ababc</a> add some tests</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/6e810451bb57c5be5872151823088f13d620068a">6e81045</a> add some fixes and workarounds of FF30- typed arrays bug that does not properly convert objects to numbers</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/e2e9036d0709915264e23dfea39102a834922437">e2e9036</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/8c7133964e6223bb1f12daca71c2c5415d9470a2">8c71339</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/1bc6dab824b3b0c51de0f0c2d0c1052a4ce1bf93">1bc6dab</a> add &#x60;sideEffects: false&#x60; to &#x60;core-js-(builder|compat)&#x60;</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/6ae7c284507ec836a5d25e4352f062c1dc8f79f8">6ae7c28</a> add &#x60;sideEffects&#x60; field to &#x60;core-js-pure&#x60; &#x60;package.json&#x60; for better tree shaking, close #1117</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/0d3dc64caaa80d2ec3fc13f7caac984b335a249a">0d3dc64</a> oops, remove some mistakenly uploaded changes</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/c191a76a7d5b64874c5e5a9b5db2a4a70734c7ed">c191a76</a> adapt some tests to a FF &lt; 23 bug</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/9d191481ca23211d4424063f4500ffe2d22f552a">9d19148</a> update dependencies and linting settings</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/5133a076d400bb428a69b07d6154064e5c8ddf0b">5133a07</a> update Electron 21 compat data mapping</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/b1039c45833f578198a7419e514dd5e779d8b988">b1039c4</a> update dependencies</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/b7f7862fd50ce66ee3540a87fbbfa0a6d54158e2">b7f7862</a> extract &#x60;CreateIterResultObject&#x60; abstraction for avoiding inconsistency in the future</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/10519a17a94714c5d98f928169ca5fd6e50ba31d">10519a1</a> just in case of future reusage, add &#x60;semver.prototype.toString&#x60;</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/8a7d9e706b695629029cdfcea0a706089b6cd235">8a7d9e7</a> use &#x60;Object.hasOwn&#x60; if it&#x27;s available in &#x60;core-js-compat&#x60; helpers</li>
      <li><a href="https://snyk.io/redirect/github/zloirock/core-js/commit/04e356639195eba196bf35ee807a4b2db93a8b97">04e3566</a> drop &#x60;semver&#x60; from the ignore of updating</li>
    </ul>

   <a href="https://snyk.io/redirect/github/zloirock/core-js/compare/e4b27bdc440039ffc2d29ec97628c3e727108a37...3c2e601b9a58af4dca0cd13aa943ab66b3deb83d">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/acinader/project/3e039b91-2450-4b56-8420-baf56cab388e?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/acinader/project/3e039b91-2450-4b56-8420-baf56cab388e/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/acinader/project/3e039b91-2450-4b56-8420-baf56cab388e/settings/integration?pkg&#x3D;core-js&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by damianstasik** [comment]
Not needed, will be upgraded to latest version in #1946

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)

**Pull request merged**
