### PR TITLE
fix: File extension is hidden in file field when editing object in modal dialog in data browser

### LINKED ISSUE #2470: The file extension is hidden beneath the icon within the file cell in the edit modal
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Screenshot 2023-06-20 at 6 47 24 PM

### Steps to reproduce

Upload any file.

### Actual Outcome

The file extension is hidden.

### Expected Outcome

The file name along with its extension should be clearly visible.

Dashboard
- Parse Dashboard version: `5.1.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64)`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS `
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

### PR DESCRIPTION
**Pull request by AshishBarvaliya**
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

Closes: #2470

### CODE REVIEW

**Comment by mtrezza** [comment]
Could you add a screen recording of what this PR fixes?

**Comment by AshishBarvaliya** [comment]
Rather than implementing changes to the common pill component to adjust the file cell styles in EditRowDialog, I have devised a new style class. This modification enhances the readability of file names along with their extensions.

Before changes - 
Screenshot 2023-06-24 at 1 27 33 PM


After changes - 
Screenshot 2023-06-24 at 1 25 42 PM

**Comment by mtrezza** [comment]
Which parts of the UI does this affect? Is this the "Add row with modal" dialog?

**Comment by AshishBarvaliya** [comment]
yes

**Comment by mtrezza** [comment]
I only see en empty field when uploading a file with modal:

image

Tried in preview and locally.

**Comment by AshishBarvaliya** [comment]
This open PR fixes that issue : #2471  (issue: #2418 )

**Comment by mtrezza** [comment]
So we need to merge #2471 first, then this PR?

**Comment by AshishBarvaliya** [comment]
Save the object(row) first, and then you'll be able to view the uploaded file.

**Comment by mtrezza** [comment]
Then I still don't fully understand what this PR fixes. Could you please upload a screen recording (not screenshot) of the bug vs. fixed?

**Comment by AshishBarvaliya** [comment]
Before: 
CPT2306262126-1181x641


After: 
CPT2306262127-1135x635


It's essentially a minor style fix where previously the file was displayed as '666162,' but after the changes, it now appears as '666162.png'.

**Comment by mtrezza** [comment]
Got it, that is when editing an existing row, I was able to duplicate that, thanks for the videos.

**Review by mtrezza — APPROVED** [review]
Looks good, tested locally

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.26](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.26)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)

**Pull request merged**
